eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9002
  context-path: /OnlineES
  jsp-servlet:
    init-parameters:
      development: true
spring:
  application:
    name: teacher-client
  datasource:
    url: jdbc:mysql://107.170.204.204:3306/onlineES?useUnicode=true&characterEncoding=utf-8
    sql-script-encoding: utf-8
    username: online
    password: online
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
logging:
  config: classpath:logback.xml

file:
  path: /online/upload

email:
  url: http://localhost:9001/OnlineES/exam/verify/



#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000