eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

#  instance:
#    ip-address: 120.79.89.98
#    hostname: 120.79.89.98

server:
  port: 9007
spring:
  application:
    name: export-client

logging:
  config: classpath:logback.xml

file:
  export:
    path: /online/export
    zipPath: /online/zip