eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

#  instance:
#    ip-address: 120.79.89.98
#    hostname: 120.79.89.98

server:
  port: 9006
spring:
  application:
    name: import-client
logging:
  config: classpath:logback.xml