<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage"><pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="512"><pkg:xmlData><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail" Target="docProps/thumbnail.jpeg"/></Relationships></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/_rels/document.xml.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="256"><pkg:xmlData><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Target="webSettings.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/></Relationships></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"><pkg:xmlData><w:document mc:Ignorable="w14 w15 wp14" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"><w:body><w:p w14:paraId="59564A22" w14:textId="19D94B7F" w:rsidR="00987D4F" w:rsidRDefault="00987D4F" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/><w:rPr><w:sz w:val="40"/></w:rPr></w:pPr><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="40"/></w:rPr><w:t>${eName}</w:t></w:r><w:r w:rsidR="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="40"/></w:rPr><w:t>-</w:t></w:r><w:r w:rsidR="006F0372"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="40"/></w:rPr><w:t>答</w:t></w:r><w:r w:rsidR="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="40"/></w:rPr><w:t>卷</w:t></w:r></w:p><w:p w14:paraId="11BFAC7D" w14:textId="6DE1B1DB" w:rsidR="009026B1" w:rsidRPr="009026B1" w:rsidRDefault="009026B1" w:rsidP="009026B1"><w:pPr><w:jc w:val="left"/><w:rPr><w:sz w:val="32"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="32"/></w:rPr><w:t>一、</w:t></w:r><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="32"/></w:rPr><w:t>基本信息：</w:t></w:r></w:p><w:tbl><w:tblPr><w:tblStyle w:val="a3"/><w:tblW w:w="0" w:type="auto"/><w:tblLook w:val="04A0" w:firstRow="1" w:lastRow="0" w:firstColumn="1" w:lastColumn="0" w:noHBand="0" w:noVBand="1"/></w:tblPr><w:tblGrid><w:gridCol w:w="1980"/><w:gridCol w:w="2158"/><w:gridCol w:w="2079"/><w:gridCol w:w="2073"/></w:tblGrid><w:tr w:rsidR="009026B1" w14:paraId="4146D44B" w14:textId="77777777" w:rsidTr="006F0372"><w:trPr><w:trHeight w:val="590"/></w:trPr><w:tc><w:tcPr><w:tcW w:w="1980" w:type="dxa"/></w:tcPr><w:p w14:paraId="7A47EC11" w14:textId="7FEDE656" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>姓名：${sName}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2158" w:type="dxa"/></w:tcPr><w:p w14:paraId="3438472E" w14:textId="64AA7FC1" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>学号：${number}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2079" w:type="dxa"/></w:tcPr><w:p w14:paraId="6E0F850D" w14:textId="21952D7D" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>班级：${className}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2073" w:type="dxa"/></w:tcPr><w:p w14:paraId="64703FA7" w14:textId="6DB23AEE" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>年级：${gradeName}</w:t></w:r></w:p></w:tc></w:tr><w:tr w:rsidR="00AA2C51" w14:paraId="32DD3610" w14:textId="77777777" w:rsidTr="00AA2C51"><w:trPr><w:trHeight w:val="590"/></w:trPr><w:tc><w:tcPr><w:tcW w:w="1980" w:type="dxa"/></w:tcPr><w:p w14:paraId="461E6200" w14:textId="2C808BA6" w:rsidR="00AA2C51" w:rsidRDefault="00AA2C51" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>科目：${courseName}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2158" w:type="dxa"/></w:tcPr><w:p w14:paraId="761D1F06" w14:textId="15E426E3" w:rsidR="00AA2C51" w:rsidRDefault="008727E1" w:rsidP="00CF39F1"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>是否</w:t></w:r><w:r w:rsidR="00AA2C51"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>缺考：</w:t></w:r><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${state}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2079" w:type="dxa"/></w:tcPr><w:p w14:paraId="0E9BA1A6" w14:textId="11348910" w:rsidR="00AA2C51" w:rsidRDefault="00AA2C51" w:rsidP="00CF39F1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>总</w:t></w:r><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>分：${totalScore}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2073" w:type="dxa"/></w:tcPr><w:p w14:paraId="7236941E" w14:textId="1AA37FD0" w:rsidR="00AA2C51" w:rsidRDefault="00AA2C51" w:rsidP="00CF39F1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>得分：${score}</w:t></w:r></w:p></w:tc></w:tr><w:tr w:rsidR="006F0372" w14:paraId="1A72C76F" w14:textId="77777777" w:rsidTr="006F0372"><w:trPr><w:trHeight w:val="604"/></w:trPr><w:tc><w:tcPr><w:tcW w:w="1980" w:type="dxa"/></w:tcPr><w:p w14:paraId="1D2198D1" w14:textId="1568E0DA" w:rsidR="006F0372" w:rsidRDefault="006F0372" w:rsidP="009B43C1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>考试时间：</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="6310" w:type="dxa"/><w:gridSpan w:val="3"/></w:tcPr><w:p w14:paraId="2CF0517C" w14:textId="744127DB" w:rsidR="006F0372" w:rsidRDefault="006F0372" w:rsidP="00CF39F1"><w:pPr><w:jc w:val="center"/></w:pPr><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/><w:r w:rsidRPr="009026B1"><w:t>${examTime}</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p w14:paraId="27529A68" w14:textId="1F85F6BA" w:rsidR="009B43C1" w:rsidRDefault="009B43C1" w:rsidP="00CF39F1"><w:pPr><w:jc w:val="left"/></w:pPr></w:p><w:p w14:paraId="2847BCAC" w14:textId="1F9E8F1F" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009026B1"><w:pPr><w:jc w:val="left"/><w:rPr><w:sz w:val="32"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="32"/></w:rPr>

    <w:t>二、题目</w:t></w:r><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/><w:sz w:val="32"/></w:rPr><w:t>信息：</w:t></w:r></w:p><w:tbl><w:tblPr><w:tblStyle w:val="a3"/><w:tblW w:w="0" w:type="auto"/><w:tblLook w:val="04A0" w:firstRow="1" w:lastRow="0" w:firstColumn="1" w:lastColumn="0" w:noHBand="0" w:noVBand="1"/></w:tblPr><w:tblGrid><w:gridCol w:w="2263"/><w:gridCol w:w="2552"/><w:gridCol w:w="1166"/><w:gridCol w:w="1275"/><w:gridCol w:w="1034"/></w:tblGrid><w:tr w:rsidR="006F0372" w14:paraId="05A49878" w14:textId="41F623DE" w:rsidTr="006F0372"><w:tc><w:tcPr><w:tcW w:w="2263" w:type="dxa"/></w:tcPr><w:p w14:paraId="0EF69E39" w14:textId="0480D313" w:rsidR="006F0372" w:rsidRPr="009026B1" w:rsidRDefault="006F0372" w:rsidP="009026B1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>题目</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2552" w:type="dxa"/></w:tcPr><w:p w14:paraId="2620A9E1" w14:textId="5D2E32C7" w:rsidR="006F0372" w:rsidRPr="009026B1" w:rsidRDefault="006F0372" w:rsidP="009026B1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>选项</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1166" w:type="dxa"/></w:tcPr><w:p w14:paraId="4E21E6EB" w14:textId="505EE2F2" w:rsidR="006F0372" w:rsidRPr="009026B1" w:rsidRDefault="006F0372" w:rsidP="009026B1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r w:rsidRPr="009026B1"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>答案</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1275" w:type="dxa"/></w:tcPr><w:p w14:paraId="4F728C5E" w14:textId="57C7E10A" w:rsidR="006F0372" w:rsidRPr="009026B1" w:rsidRDefault="006F0372" w:rsidP="009026B1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>考生选择</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1034" w:type="dxa"/></w:tcPr><w:p w14:paraId="1ACAC05A" w14:textId="2A112263" w:rsidR="006F0372" w:rsidRPr="009026B1" w:rsidRDefault="006F0372" w:rsidP="009026B1"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>得分</w:t></w:r></w:p></w:tc></w:tr>

<#list list as question>
    <w:tr w:rsidR="006F0372" w14:paraId="34FD4C93" w14:textId="6F41F68A" w:rsidTr="006F0372"><w:trPr><w:trHeight w:val="647"/></w:trPr><w:tc><w:tcPr><w:tcW w:w="2263" w:type="dxa"/></w:tcPr><w:p w14:paraId="1679F7EE" w14:textId="633531E8" w:rsidR="006F0372" w:rsidRPr="004554AC" w:rsidRDefault="006F0372" w:rsidP="004554AC"><w:pPr><w:jc w:val="left"/></w:pPr><w:r w:rsidRPr="004554AC"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${question.question}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2552" w:type="dxa"/></w:tcPr><w:p w14:paraId="6029321C" w14:textId="7EB8AAE4" w:rsidR="006F0372" w:rsidRPr="004554AC" w:rsidRDefault="006F0372" w:rsidP="004554AC"><w:pPr><w:jc w:val="left"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${question.optionStr}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1166" w:type="dxa"/></w:tcPr><w:p w14:paraId="27745568" w14:textId="31563D85" w:rsidR="006F0372" w:rsidRPr="004554AC" w:rsidRDefault="006F0372" w:rsidP="004554AC"><w:pPr><w:jc w:val="center"/></w:pPr><w:r w:rsidRPr="004554AC"><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${question.tAnswer}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1275" w:type="dxa"/></w:tcPr><w:p w14:paraId="58AD86FF" w14:textId="0D6B0ABC" w:rsidR="006F0372" w:rsidRPr="004554AC" w:rsidRDefault="006F0372" w:rsidP="004554AC"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${question.sAnswer}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="1034" w:type="dxa"/></w:tcPr><w:p w14:paraId="509BEEAA" w14:textId="5E877C4D" w:rsidR="006F0372" w:rsidRPr="004554AC" w:rsidRDefault="006F0372" w:rsidP="004554AC"><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/></w:rPr><w:t>${question.score}</w:t></w:r></w:p></w:tc></w:tr>
</#list>

</w:tbl><w:p w14:paraId="1F06EA25" w14:textId="79AACB57" w:rsidR="009026B1" w:rsidRDefault="009026B1" w:rsidP="009026B1"><w:pPr><w:jc w:val="left"/></w:pPr></w:p><w:sectPr w:rsidR="009026B1" w:rsidSect="000335F9"><w:pgSz w:w="11900" w:h="16840"/><w:pgMar w:top="1440" w:right="1800" w:bottom="1440" w:left="1800" w:header="851" w:footer="992" w:gutter="0"/><w:cols w:space="425"/><w:docGrid w:type="lines" w:linePitch="312"/></w:sectPr></w:body></w:document></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/theme/theme1.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.theme+xml"><pkg:xmlData><a:theme name="Office 主题" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="44546A"/></a:dk2><a:lt2><a:srgbClr val="E7E6E6"/></a:lt2><a:accent1><a:srgbClr val="4472C4"/></a:accent1><a:accent2><a:srgbClr val="ED7D31"/></a:accent2><a:accent3><a:srgbClr val="A5A5A5"/></a:accent3><a:accent4><a:srgbClr val="FFC000"/></a:accent4><a:accent5><a:srgbClr val="5B9BD5"/></a:accent5><a:accent6><a:srgbClr val="70AD47"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="Office"><a:majorFont><a:latin typeface="DengXian Light" panose="020F0302020204030204"/><a:ea typeface=""/><a:cs typeface=""/><a:font script="Jpan" typeface="ＭＳ ゴシック"/><a:font script="Hang" typeface="맑은 고딕"/><a:font script="Hans" typeface="DengXian Light"/><a:font script="Hant" typeface="新細明體"/><a:font script="Arab" typeface="Times New Roman"/><a:font script="Hebr" typeface="Times New Roman"/><a:font script="Thai" typeface="Angsana New"/><a:font script="Ethi" typeface="Nyala"/><a:font script="Beng" typeface="Vrinda"/><a:font script="Gujr" typeface="Shruti"/><a:font script="Khmr" typeface="MoolBoran"/><a:font script="Knda" typeface="Tunga"/><a:font script="Guru" typeface="Raavi"/><a:font script="Cans" typeface="Euphemia"/><a:font script="Cher" typeface="Plantagenet Cherokee"/><a:font script="Yiii" typeface="Microsoft Yi Baiti"/><a:font script="Tibt" typeface="Microsoft Himalaya"/><a:font script="Thaa" typeface="MV Boli"/><a:font script="Deva" typeface="Mangal"/><a:font script="Telu" typeface="Gautami"/><a:font script="Taml" typeface="Latha"/><a:font script="Syrc" typeface="Estrangelo Edessa"/><a:font script="Orya" typeface="Kalinga"/><a:font script="Mlym" typeface="Kartika"/><a:font script="Laoo" typeface="DokChampa"/><a:font script="Sinh" typeface="Iskoola Pota"/><a:font script="Mong" typeface="Mongolian Baiti"/><a:font script="Viet" typeface="Times New Roman"/><a:font script="Uigh" typeface="Microsoft Uighur"/><a:font script="Geor" typeface="Sylfaen"/></a:majorFont><a:minorFont><a:latin typeface="DengXian" panose="020F0502020204030204"/><a:ea typeface=""/><a:cs typeface=""/><a:font script="Jpan" typeface="ＭＳ 明朝"/><a:font script="Hang" typeface="맑은 고딕"/><a:font script="Hans" typeface="DengXian"/><a:font script="Hant" typeface="新細明體"/><a:font script="Arab" typeface="Arial"/><a:font script="Hebr" typeface="Arial"/><a:font script="Thai" typeface="Cordia New"/><a:font script="Ethi" typeface="Nyala"/><a:font script="Beng" typeface="Vrinda"/><a:font script="Gujr" typeface="Shruti"/><a:font script="Khmr" typeface="DaunPenh"/><a:font script="Knda" typeface="Tunga"/><a:font script="Guru" typeface="Raavi"/><a:font script="Cans" typeface="Euphemia"/><a:font script="Cher" typeface="Plantagenet Cherokee"/><a:font script="Yiii" typeface="Microsoft Yi Baiti"/><a:font script="Tibt" typeface="Microsoft Himalaya"/><a:font script="Thaa" typeface="MV Boli"/><a:font script="Deva" typeface="Mangal"/><a:font script="Telu" typeface="Gautami"/><a:font script="Taml" typeface="Latha"/><a:font script="Syrc" typeface="Estrangelo Edessa"/><a:font script="Orya" typeface="Kalinga"/><a:font script="Mlym" typeface="Kartika"/><a:font script="Laoo" typeface="DokChampa"/><a:font script="Sinh" typeface="Iskoola Pota"/><a:font script="Mong" typeface="Mongolian Baiti"/><a:font script="Viet" typeface="Arial"/><a:font script="Uigh" typeface="Microsoft Uighur"/><a:font script="Geor" typeface="Sylfaen"/></a:minorFont></a:fontScheme><a:fmtScheme name="Office"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:lumMod val="110000"/><a:satMod val="105000"/><a:tint val="67000"/></a:schemeClr></a:gs><a:gs pos="50000"><a:schemeClr val="phClr"><a:lumMod val="105000"/><a:satMod val="103000"/><a:tint val="73000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:lumMod val="105000"/><a:satMod val="109000"/><a:tint val="81000"/></a:schemeClr></a:gs></a:gsLst><a:lin ang="5400000" scaled="0"/></a:gradFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:satMod val="103000"/><a:lumMod val="102000"/><a:tint val="94000"/></a:schemeClr></a:gs><a:gs pos="50000"><a:schemeClr val="phClr"><a:satMod val="110000"/><a:lumMod val="100000"/><a:shade val="100000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:lumMod val="99000"/><a:satMod val="120000"/><a:shade val="78000"/></a:schemeClr></a:gs></a:gsLst><a:lin ang="5400000" scaled="0"/></a:gradFill></a:fillStyleLst><a:lnStyleLst><a:ln w="6350" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/><a:miter lim="800000"/></a:ln><a:ln w="12700" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/><a:miter lim="800000"/></a:ln><a:ln w="19050" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/><a:miter lim="800000"/></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst><a:outerShdw blurRad="57150" dist="19050" dir="5400000" algn="ctr" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="63000"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"><a:tint val="95000"/><a:satMod val="170000"/></a:schemeClr></a:solidFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="93000"/><a:satMod val="150000"/><a:shade val="98000"/><a:lumMod val="102000"/></a:schemeClr></a:gs><a:gs pos="50000"><a:schemeClr val="phClr"><a:tint val="98000"/><a:satMod val="130000"/><a:shade val="90000"/><a:lumMod val="103000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="63000"/><a:satMod val="120000"/></a:schemeClr></a:gs></a:gsLst><a:lin ang="5400000" scaled="0"/></a:gradFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/><a:extLst><a:ext uri="{05A4C25C-085E-4340-85A3-A5531E510DB2}"><thm15:themeFamily name="Office Theme" id="{62F939B6-93AF-4DB8-9C6B-D6C7DFDC589F}" vid="{4A3C46E8-61CC-4603-A589-7422A47A8E4A}" xmlns:thm15="http://schemas.microsoft.com/office/thememl/2012/main"/></a:ext></a:extLst></a:theme></pkg:xmlData></pkg:part><pkg:part pkg:name="/docProps/thumbnail.jpeg" pkg:contentType="image/jpeg" pkg:compression="store"><pkg:binaryData>/9j/4AAQSkZJRgABAQAASABIAAD/4QCARXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUA
AAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQAD
AAAAAQABAACgAgAEAAAAAQAAAWmgAwAEAAAAAQAAAgAAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJ
TQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/AABEIAgABaQMBEQACEQEDEQH/
xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMA
BBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVG
R0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0
tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEB
AQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2Fx
EyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZ
WmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TF
xsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/
3QAEAC7/2gAMAwEAAhEDEQA/AP7Yfgx8GPg9N8HvhRLL8KPhrLLL8NfAskkkngTws8kkj+F9LZ3d
200s7uxLMzHczEk5JNAHpX/ClPg3/wBEl+GX/hBeFf8A5W0AH/ClPg3/ANEl+GX/AIQXhX/5W0AH
/ClPg3/0SX4Zf+EF4V/+VtAB/wAKU+Df/RJfhl/4QXhX/wCVtAB/wpT4N/8ARJfhl/4QXhX/AOVt
AB/wpT4N/wDRJfhl/wCEF4V/+VtAB/wpT4N/9El+GX/hBeFf/lbQAf8AClPg3/0SX4Zf+EF4V/8A
lbQAf8KU+Df/AESX4Zf+EF4V/wDlbQAf8KU+Df8A0SX4Zf8AhBeFf/lbQAf8KU+Df/RJfhl/4QXh
X/5W0AH/AApT4N/9El+GX/hBeFf/AJW0AH/ClPg3/wBEl+GX/hBeFf8A5W0AH/ClPg3/ANEl+GX/
AIQXhX/5W0AH/ClPg3/0SX4Zf+EF4V/+VtAB/wAKU+Df/RJfhl/4QXhX/wCVtAB/wpT4N/8ARJfh
l/4QXhX/AOVtAB/wpT4N/wDRJfhl/wCEF4V/+VtAB/wpT4N/9El+GX/hBeFf/lbQAf8AClPg3/0S
X4Zf+EF4V/8AlbQAf8KU+Df/AESX4Zf+EF4V/wDlbQAf8KU+Df8A0SX4Zf8AhBeFf/lbQAf8KU+D
f/RJfhl/4QXhX/5W0AH/AApT4N/9El+GX/hBeFf/AJW0AH/ClPg3/wBEl+GX/hBeFf8A5W0AH/Cl
Pg3/ANEl+GX/AIQXhX/5W0AH/ClPg3/0SX4Zf+EF4V/+VtAB/wAKU+Df/RJfhl/4QXhX/wCVtAB/
wpT4N/8ARJfhl/4QXhX/AOVtAB/wpT4N/wDRJfhl/wCEF4V/+VtAB/wpT4N/9El+GX/hBeFf/lbQ
Af8AClPg3/0SX4Zf+EF4V/8AlbQAf8KU+Df/AESX4Zf+EF4V/wDlbQAf8KU+Df8A0SX4Zf8AhBeF
f/lbQAf8KU+Df/RJfhl/4QXhX/5W0AH/AApT4N/9El+GX/hBeFf/AJW0AH/ClPg3/wBEl+GX/hBe
Ff8A5W0AH/ClPg3/ANEl+GX/AIQXhX/5W0AH/ClPg3/0SX4Zf+EF4V/+VtAB/wAKU+Df/RJfhl/4
QXhX/wCVtAB/wpT4N/8ARJfhl/4QXhX/AOVtAB/wpT4N/wDRJfhl/wCEF4V/+VtAB/wpT4N/9El+
GX/hBeFf/lbQAf8AClPg3/0SX4Zf+EF4V/8AlbQB/Nd/wrT4c/8ARP8AwT/4Sug//INAH//Q/ur+
Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9H+6v4Kf8ka+En/AGTL
wH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUA
FABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/0v7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAfzL0Af/T/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQB/MvQB/9T+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAIzKoLMQoHUscAfUnGP8APXOKABmCgsxCqBksxAAHqScAD8fyoAqahqOn6TZXOparfWem
adZxma7v9QuYbOytYQcGW5urh44IIwSAXldFBOCRkUAWY5I5VLRSJIoeSMtG6uokhkaKVCVJAeKV
HikX7ySIyMAykKAVbTUtOv59StrHULK8udGvU03V7e0u4LifStRk0+w1ePT9Sihd5LG9k0rVdM1N
LS6WKdtP1GwvQhtry3kcAu0AUrDUtO1SGS40y/stRt4b3UNNmnsLqC8hi1HSL+50vVrCSW3kkSO9
0zU7S707ULVmE9lf2tzaXMcVxDLEoAajqenaPaSahq2oWWl2ELwRy3uo3cFlaRPdXEVrbJJc3Lxw
o9xdTw20Cs4MtxNFDHukkRaAGpqulyapc6HHqVhJrdlYWOq3mjpeW76paaXqdxqFnpupXOnrKbuC
w1C70jVbWxvJYUt7u40zUIbeWSWyuUiAJp7yztZLSK6ura2l1C5NnYRzzxQyXt4La5vTa2iSMrXN
yLOzu7swQh5RbWtzOVMUEjIAWaACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/mXoA/9X+
6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfGf/AAUG0ex1
z9j342WWtxeLpPClpoGm+JfHn/CFah4W0rVj8OvBPiLR/G3xBtb6/wDF/j34a6VbeF9W8G+Hdb0P
xjND4ts9Xi8K6pq8mi2Wr6mttpV2AfyD+DvgR8A9S8dX9lD8Kf2h/A3iS21CTwL4h8S2cHgfR9dv
PEOjanp1rY+MPAt34k/al0zQ7Zvh9qXxV8EeE7jVZhZaLY/ES0XRvEJiuH/00A/fP/grD4u+LOgf
D34n+CPDvxA+KGk3vxl/Z71a++FHgbQNe+C3iPT9L+K3h290HR9S0n4ofDm5+CPjD4kaB8GbeHVt
C8SeKfjXovxK8V+FdJ1dPEfhbWR4U1LWPhZY/EIA9a/ZKHiaL9mv9oj4lQ/FLwt8DvDXizx54r1n
V7b406j4K1VvgVqmlXd9F+0FcfGvS/gPon7Ien/C7416j4rm8SXnjybw/wDFbXdO0PWLbR/HVp4w
1LU73W9U8QgH5AfCG/8AiBcft1+P7bT/AIq6zqthpnxg+HXxV+Gnw8+Jepa8lt8bvH3jL4QfCz4e
fDP4la18C/2ov+Cv3hH4m6nH4M0/4Tf8JR8HbLxDoPiD4gayfGmjeLtV8PaJpHhz4IWUQB+uv7Rv
jD4tfB34r/HX4nWMhh8R/Dr9lbwP8U/G/iT4Fw6b4f1zxn8O/CN38Shr+m+JfAfxt8ReOfhXqOpa
Hruh+Ida8Ca7aWdt4+0rQdXPgiXxXqelPeyzgHS/sAfD7U/g34K+PXxk+IfjX4k614qvvi9+0jZ/
Ff4aWHg+y8W3mi61aftOfGb4maFqmneDfgx4SutQ8T+OtX8LfE+DUr2+8IeHtQ1PxXo2u+HtPWO/
0Lwr4K07QQDC/wCClmuaL8Yf2VtE8QW3wu/aL8d/D2W+8Ra9ceGF8aaX+xHoNl4z8Pv/AGB8KNb+
NviP48P8Lvjr4Kfw98Wb3w74v+Ci/D7w7e3t98UNC8FeL9T0q88PadousRAH50/sLeEdS039qnwh
q+q+G/jJ+0P8ULjSNN8W+MfiLb/tL/CzwJ4w1vQrDW/APhbUV8Yfs/QftSfFrwn4/wDgp+zZ4j1f
R/FPgXW9G8b+D/G/hrSfiD4j8Nah4M+L3jjx9428Q/EwA8Y/aO+JPxJ+Lf7Q3x9+IHhvxN8QdQ8A
/C34ZeKPjp4r8UfAvxt8Z/FXwx1bWvE/wx/aF/Zz8G638Dfit4I/4Je+MvCvhvWPCXwfHxz+G/i7
44Lczyau9l4C022+L2q6p8HdbTwwAf0H/wDBPL4kav8AEL9nPQ7bXtObw/qfgW5sfB0Xg+/tdS0n
xL4J0KLwp4a1vwz4Q8V+G7z9nj9mfT/DOqeHdE1q00jTdO8L+AdW8J3/AIWs/D3iXQPHPimy15Li
AA+56ACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD+ZegD//W/ur+Cn/JGvhJ/wBky8B/+orp
VAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAHCfFL4d+H/i98MviL8JvFjagvhX4oeBPF3w
78TNpNyllqi+H/Gvh/UPDWstpt5JBcx2moDTtTuTZ3MltcJBceXK0EqqUYA8S8dfscfBTx1e2eoz
2Xinw9fR+L9a8WaxceG/F2swDxQniv4geBfif418L67batPrFn/wi/jLxp8NPA2qa1aaNb6NqdrD
oEel+HtX0LS9R1my1IA1Pin+yt8Mfih/wmlxjUvAOt/FPVPAMnxj8V+AtP8ABdr4v+LnhD4cpNFo
Pww8aeJvFHhHxXq0XgEwzzxPa+Erjwt4j0w3WpXHhrxNoF3reuXGpAHW61+zn8BPEvizxL458R/B
z4beIPFnjK5+G9/4r1vXPB+h6tdeIdV+D+ry678LNc1ddQs7m3vvEPw+1aVb3wl4hnhbW9DktNNS
xv4YtK02O0AOb8Wfs8J46+MXhH4o+LvjB8WNb8K+A9d07xj4S+AUsfwosvg3pXjzSfDureHNM8bX
M+l/Cyx+MXiHVdPj1vUNasNH8T/F3WvBen+JxpviKy8Kw6poWgXGlgHGfHD9hr9n79oz4gzfEX4u
6b478QalcfDe2+FFxoejfFX4j+A/Ct34MTVPFeo6rYajo3w/8TeFhrD+JrbxlrfhvxM+s3Goxar4
MvNR8HNBF4b8R+LtN8QgHXfDj9lf4WfCL4p6v8T/AIat4s8Gw634LtPCGo/C7Q/E99ZfBqe+tLTw
Xoy/EJ/h3GBpk3xMk8JfDjwJ4JbxhcSzXcHhTw1Dp9lDa3Gr+JL3WgDv/jL8JfD3xx+H2pfDbxTq
fifRtF1TWfBeuTan4M1p/Dnia1vfAvjbw7490dtL16GCe70iSTWPDNhDcX+m/ZdXt7OS4k0fUtK1
QWep2gB5/wCDP2XfAfgb4saF8Y9N8W/GfXPFHh74eeP/AIZ2Fj4++M3xC+Jnh5dA+I/iT4X+Kdeu
o9M+IOu+JZdO1mLUfhN4aisb7RbzS0ayuNVt9TttTMmmyaWAc/8AG79kPwX8cfE2r+J9W8ZeLfDU
nibwp8P/AAd4w0Gw8JfAb4g+EfFul/Cjxb4z8cfDW51bwt8evgx8YtHtNX8F+J/iB4s1XR9V8P22
iXb3WpW82ovfzaLoUmmgHunwx+HekfCrwTo/gbRNU8Ta5Z6VNrN9ca74z1688TeKdd1nxHrmpeJv
EWua5rN8d9xf6xr+sanqUlvaQ2WkaaLpdM0LTNK0WzsNNtQDvaACgAoAKACgAoAKACgAoAKACgAo
AKACgAoAKACgD+ZegD//1/7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAUdU1TTNE0zUda1r
UbHSNH0ixu9U1bVtUu7ew0zS9MsLeS7v9R1G+upIbWysbK1hlubu7uZYre2t4pJppEjR3oA8ft/2
mv2b7ueC0tf2gvgjc3V1NFb21tb/ABX8BzT3FxO4jhgghj10ySzTSMscUUYLyOwVQzECgD26gD4U
/az/AGuPGP7Mvjr4UaRZfCrS/HXg74hab4ya91Y+M59D16z1zw1Hpk8Wn2mlr4a1a3Fh9l1GK4uN
SnupHnkmW0hs7c273NwAXPBH7XPiD/hj74X/ALVXxP8AhBrkNp4x+EPhr4u+KNJ+F2ueEvEFv4W8
Pa/4L0jxhBdbPHPiXwBqWo3N5Hqg0/TPDHh6DxP4ku9TWLS7G11K8ubYzgHlHhb/AIKQaLqn7Ck3
7ZfiL4W+MvDNpB8J7TxDpumasvhtNP8AHHxckim0G5+GPhfTPDPi3xx460l4/iNaXPh68vPF/hnR
/wCwNGjufEmsyRaVpWr3lkAeifDH9rj4keKvjdcfB/xZ+zb8WtDsvJ0rR4PHY8Kx6b4XsvGejL4g
j+JR1LV73xFfeHrnwJa/2Tp+p+BfEuh+ItU1fxLHqd1op8MLc6dpuq+IgDxmz/4Kh+EJf2h9W+DN
x4V00aevxr0j9nnRUg1zXW8dP8QYvjj4k+C/ijW9U0uXwdH4Pj8IpPH4V8Q6Elp4zl1iTSn8Qm/i
TUYtN0iUA/Ue+1JbG50e1az1G5Os6jLpqTWNjNd22nNFpOqaubzWJ4gU0zTnTSnsIr64xC+rX2l6
cCZ9QgFAGjQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFAH8y9AH//Q/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQBHNDFcRSwTxRzwTxvDNDMiyRT
RSKUkiljcMkkciMUdHVlZWKsCCRQBkDwz4bUhh4f0QFSCCNKsQQQcggiDIIIBBHQ80AZXh/RfFel
6/4xu9Y8ZnxL4b1vUNO1Hwnod34f0/T9T8EhbBbTWtFTX9Mlto/EXh+8u7e31bRo9V0VfEOjXt5r
lve+Jdf0q50LTvDIB+fn7Z//AAT9n/af8YW3jnw94p8HeGvFEWl6TpUOueKvhp8MvFt9oNnpusaV
qF7beH7nV/hvquslvEFppv8AZ99qmr69qGraVaXF7pHh250rwzrninQNfANP4S/8E8dD+Hnwx8K/
DaL4neMPB+heFfiLcfFax8JfC/SPhJpHgQ+PrPUPBOoeEPEl14f1f4QXtprC+B7rwY2peDfCevWu
o+BfBura3b3fhXw1pP8AwrT4HJ8KwCz8Nv2EdU+G/wCzf8QPhLafGfxpr3iz4ofsyQ/BjxfDr7eE
v+FXS+P7T4Saf8LtO+JGl+HvDfgDwxqmlX1jpWmWWh3V3p9xa3Pinw1ZabL4ztPEXiXStK1ewAI/
A37EfjLwZ8drf46w/EDwPJr0nxh+PXjzVHHhz4sXWr6j4S+JsPxhi8EeFNTk1P443vgO8h8Hnxr4
EbUIdB+Gfgy5vYvBrW2n67Yma4uNUAOHT/gnh4wtfiXfeONP+JHwij1C91jS/GsnxC1H9mv4Z6n8
RV+IOl+H/B+rf8JVDYmwtPCdj4l1D48eGNY+L2reNNMt7LXtT0n4heNfAt3E+tw+Bvid4JAP1Bvb
K6urnR54NY1DTYtM1GS9vrOyh0qS28Q2z6RqmnLpGrNqOmaheW+nw3uoWmvxy6FdaNqx1XRNMgm1
OXQ5tY0jVQDSoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAo
AKACgD+ZegD/0f7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAfMv7XUupD4O2Njpmv8Aifwz
J4h+On7Kfg/UNX8G+Jtd8HeJI/D/AI1/am+DXhHxRY6d4m8NX+ma7pP9s+Gta1XRryfTb+2nksL+
6ty5imkRgBP+GUvAn/RRP2m//Esv2jv/AJ5FAB/wyl4E/wCiiftN/wDiWX7R3/zyKAD/AIZS8Cf9
FE/ab/8AEsv2jv8A55FAB/wyl4E/6KJ+03/4ll+0d/8APIoAP+GUvAn/AEUT9pv/AMSy/aO/+eRQ
Af8ADKXgT/oon7Tf/iWX7R3/AM8igA/4ZS8Cf9FE/ab/APEsv2jv/nkUAeI/Cj4E6P4r8eftM6Dr
nxQ/aVudM+GXxu0HwR4Ohi/ak/aBtH0/w5f/ALN/7PvxIurO4uLX4hQz6pM/i74g+Kr9b7UpLq9j
t76DTI5107TrC2twD27/AIZS8Cf9FE/ab/8AEsv2jv8A55FAB/wyl4E/6KJ+03/4ll+0d/8APIoA
P+GUvAn/AEUT9pv/AMSy/aO/+eRQAf8ADKXgT/oon7Tf/iWX7R3/AM8igA/4ZS8Cf9FE/ab/APEs
v2jv/nkUAH/DKXgT/oon7Tf/AIll+0d/88igA/4ZS8Cf9FE/ab/8Sy/aO/8AnkUAeJ2nwL0iX9o3
Xvhq/wAT/wBpM+EbD4J+EvHNrYj9qL9oAXSeI9X8deNdAvrttVHxCGpyW8umaJp0K6fJctYQyQvc
wwJcTzu4B7Z/wyl4E/6KJ+03/wCJZftHf/PIoAP+GUvAn/RRP2m//Esv2jv/AJ5FAB/wyl4E/wCi
iftN/wDiWX7R3/zyKAD/AIZS8Cf9FE/ab/8AEsv2jv8A55FAB/wyl4E/6KJ+03/4ll+0d/8APIoA
P+GUvAn/AEUT9pv/AMSy/aO/+eRQAf8ADKXgT/oon7Tf/iWX7R3/AM8igDxPwL8C9I1/4x/HbwXq
fxP/AGk5vD3gF/hkvhi1j/ai+P8AbT2Y8UeE7jV9Z+039v8AEKO91L7RfRrLD/aE1x9jQeRaeVCS
lAHtn/DKXgT/AKKJ+03/AOJZftHf/PIoAP8AhlLwJ/0UT9pv/wASy/aO/wDnkUAH/DKXgT/oon7T
f/iWX7R3/wA8igA/4ZS8Cf8ARRP2m/8AxLL9o7/55FAB/wAMpeBP+iiftN/+JZftHf8AzyKAD/hl
LwJ/0UT9pv8A8Sy/aO/+eRQAf8MpeBP+iiftN/8AiWX7R3/zyKAKn7LUF9pdr8c/C9x4k8Y+J9P8
G/H/AMVeGvD11468Y+JvHeu2OhQeD/AOowaY3iPxdqmsa5c2lve6nfzQRXN9IsLXMojVVbFAH1NQ
AUAFABQAUAFAH8y9AH//0v7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAfMv7Wv/ACSzwp/2
c1+xT/62T8BqAPpqgD8mv+ChvhP9ovxj4v0u3+Deu/Gfw/oOkfBfxU2tX/ws0OW4trm/vvFGl+JL
XwZqGpWnw38X+J5NQ+I+t/DzwdoTN4Eh8cDSPCFj4w0T4keFPB/hf4jaT4t1IAyvjvo/x48SeIvg
Jr0Ft8WLjwto/wAL/Gl5q83h3xV8f/C2vtrWitpOna1oVpofwZ/Za8L+IPBHj/xwNd07TPD/AMQ/
GumXlkvgLwt440fwF8N/COu+Krv4gMAfqboWpaprFp4P1a60zXNEOq+GRqWq6LKdNe00jUL210a5
XTNcfUra18SNqunyS3lpZGwtrW2YxaoddtorgaYiAHw3r+neJF/au8P+I7fxV8aV+Gunw+NDr3h2
z+H/AO2zP4cbxhB4u+G7+H7RrjTvievwu1ewul0/xlcaXrWn/D+f4cWvh9r2w1HTNSsNXtLiUA4n
4c/DT4/6D+0lDql7H8e9Z0rTr288ReIfFvxE1T4eN4P1u0+InxX+JMsQj0r4W/Fn4fWmtX/gn4Va
X4e8EQ6Z4j034iaX4YtB4J8Tab8MdJv9A0iHxSAfqPQB8xfAgsPij+2yUUM4/aZ8LFVLbQzD9jT9
knapbDbQTwW2tjOcHGKAPjb4AfBL9qvw3+0vr+r+JvG17e+EvB2gXYu9Q1qCa60PxP40+Kdl4k1P
WJJtMn8NaDo2vReDZNP+Hl5De/DfVfDl3pejy2vws0zXfDHg3Q7vwbKAdt+yx8Lfjt8Nvj54j0fx
7q+g674d0Xwt4x02XxB4e+HfjLw/puqWNz4l8MXXgT+1vF+t+GPB+leNfHWreHRbarrGrWfiH4xy
eG9U0zx1oGoa5p+oa6mraqAfWfx2XxfJ+z98XYvC7fEQeOZvDXjmLwX/AMIw1rF43bxHJe6mngyP
RJ/CGwWuly3x0mKyvHkg1W18KPHc+Kru11ePWbuIA+cPHv8Aw0xceJfj94nu7LxtbeCNb8FfCNvg
hpPw48Qa7c6pp+o+HvGPjC9vLe/8MQeHtF1rSfE3iKyvNO1n4jTS3EVkmlr4f+H13ca5pOjXt7qQ
Bh+PrD44eINY+JviPwNbfHPTBpPj3TG8L/D3Wbv4hLpvxAOieGPjHBDfSa/o/wAUvhnb/D7wR438
XeKPBOi6bYeCdV1ex8M6P4H8F+Nfino14/iTxXb/AA/AI/GPhz9qqbUPiQ2jWnxSaG48S+Lm8Otp
3j2C1iPime9/aVb4UaxpEb+NbaKy+Gml6Pqn7OcPjHw/b2tvol9qS2k3iTSJ08O/FRJQDpNOtfjx
o+seHrrX7b4xbU+Ivwrk16Cx1fUvEOkav4nTxN8RLf4xeI7K303WtafSvg1qPg/U/AcvhTwldy6T
4e04WzOPC8Hi7TNQuUAPbrD/AJPJ8Vf9my+AP/Vp/EugD6aoA/MD9tPQvjxrnxg8DWfw0vPipY+B
LjwnpU3jO98J+Gvinr/hW01HQfHlp4ssvtp8DfFfw9eWmutpvh2+vdPu/AngCfxe9zpun+E9R8d6
BD460F7QA+G/jB4c/bUutS8N2ng3wz+034uk174V+ALfSPEBufHGkeG5te0j4ReKfDPjnQPEVtf3
Phn4t+DPEOleLfiRP8UPDEnxW+JeqaFrGu+CvFtjp/j5/E2v/CfwT4JAP6ArO/k1SXw9qdmniCLT
NS0W5v3iutMttGhj+1x6VcWKeINI1+1s/GOk6wkUs62umJaWhsn/ALVtvEtrDew6dGgB8i+Lo/il
qPww/bb0fwwfivF4ou9f8Tv8E7y8j8XQapJNqXwm8D6fpNt8O72x8QeD72x0S3+Kmn+KodLfTvEn
h/StMilXxBqN6uhahJqN+AeSfsV6T8Y7X4tfEXXPirqfxXSz8VeCdF1zw/4Y8a+Cfjd4e0fRLm88
aeN4ord77XviP44+E6eJ7P4e2Hw6GtWf2nxH8QZ/t9muv+M7zxNpXjoakAfptQB8y/Cz/k439qn/
AK6fBH/1ALugDzD9vfwh8WfFvwssm+FFn8Q9U1DwyvjHxZeab4D1a10yU6n4f8Da7qPgLVRbaf8A
Eb4V+M9e8SaH8Q4PDN/4U0TRvFdx4fMq6pq+v+F/EmuaR4Ls0APjn9pvQv2pbLSPglD4P8EftIan
Yz6L8QvCXjc6V4lvNbXR9Z8UX3h3XNE8YeINN0DxZ8cvivHpNro+ganp9tqXhf4y2ev6NrlhYafY
aboGj+L9Y0HxiAfo1+zOvjyH9nL4I2Pjmw8c6T4+0fw94f0Dx3pmvQWi+KrDXfD8sui+IrPxTqHi
bWPEUPieO3vrGeLVPHPhPXNU03x6i/8ACa/D2+l8Na7pDMAeW/Fa2+KOr/FrxgPCtl8aNP8ADei6
P4BtNVh0rXPE1ro3xA0fUviF8JNY8fy/D6bT9Z0vw94QuPBfw00XxrplreaZeWvxW8b+KfGPizT9
LbSdO8J+GH8XAHmHifT/ANrm6+HvxT8J+C08eR/FDWv2ZPgfpcmseIvE1/pGn6B8SNP8PfEiP4sf
8Kw8TW2na/4Xl+JF6l74A019bsLu00uTxJqF14stta1B/Bx0JwDzj9uqy/ahk8ffCjVvht4K+NHi
PTJPAPhfTL+y+G+tQ3vg/SPiJb/ETRvHWo6D4wj0HwzpXxAg0H4gaT4IHw61nxjbeKZvClhe6z4K
1XxlY/DzwHpvj/UPHIB+i/7Og8RxfAT4NWXjGHXbfxlpHw08GaB4xh8TWmtWmuJ4u8PaDY6H4n/t
D/hIb7VdWvpG13T9QePWbjWddh1+BotbsfEGv2GoW2sXoBxX7OH/ACGf2m/+zm/F/wD6gXwyoA+m
6ACgAoAKACgAoA/mXoA//9P+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFAHyl+2hfXel/BPS
9T0/RdR8R3+nftDfsc31j4d0ibSLbVdevbT9r74GXFroum3Ov6nouhW9/qk8cdjaXGtaxpWlQzzx
y6hqNlaLNcIAaX/C8vjB/wBGY/H3/wALj9k//wCiRoAP+F5fGD/ozH4+/wDhcfsn/wD0SNAB/wAL
y+MH/RmPx9/8Lj9k/wD+iRoAP+F5fGD/AKMx+Pv/AIXH7J//ANEjQAf8Ly+MH/RmPx9/8Lj9k/8A
+iRoAP8AheXxg/6Mx+Pv/hcfsn//AESNAB/wvL4wf9GY/H3/AMLj9k//AOiRoA+ePgr8ZPinafEn
9ru4tf2S/jdqs+qftD+Gr7UrGz8Yfsyw3Hhq9j/ZP/Zg0yPRdVk1H9oCxs7u/n07TrDxFHcaDc6x
pS6Zr+nWs2oxa5bazpGlgH0P/wALy+MH/RmPx9/8Lj9k/wD+iRoAP+F5fGD/AKMx+Pv/AIXH7J//
ANEjQAf8Ly+MH/RmPx9/8Lj9k/8A+iRoAP8AheXxg/6Mx+Pv/hcfsn//AESNAB/wvL4wf9GY/H3/
AMLj9k//AOiRoAP+F5fGD/ozH4+/+Fx+yf8A/RI0AH/C8vjB/wBGY/H3/wALj9k//wCiRoA+e7L4
xfFEftW+JdVH7J3xtbU5P2e/BGnv4ZHi/wDZnGqwWMPxI+INxFrsl23x+XQG0+6uJ5tPhtodYl1h
LmznludMgsntbq4APoT/AIXl8YP+jMfj7/4XH7J//wBEjQAf8Ly+MH/RmPx9/wDC4/ZP/wDokaAD
/heXxg/6Mx+Pv/hcfsn/AP0SNAB/wvL4wf8ARmPx9/8AC4/ZP/8AokaAD/heXxg/6Mx+Pv8A4XH7
J/8A9EjQAf8AC8vjB/0Zj8ff/C4/ZP8A/okaAD/heXxg/wCjMfj7/wCFx+yf/wDRI0AfPfw4+MXx
Stvjz+0hfW/7J3xtv73UZPhD9v0W28X/ALM8V/4f+yeCbqG1GpXF78frXSbk6rCTeWf9i6jqohgU
pqJsrorb0AfQn/C8vjB/0Zj8ff8AwuP2T/8A6JGgA/4Xl8YP+jMfj7/4XH7J/wD9EjQAf8Ly+MH/
AEZj8ff/AAuP2T//AKJGgA/4Xl8YP+jMfj7/AOFx+yf/APRI0AH/AAvL4wf9GY/H3/wuP2T/AP6J
GgA/4Xl8YP8AozH4+/8Ahcfsn/8A0SNAB/wvL4wf9GY/H3/wuP2T/wD6JGgDC/ZJ1XUddg/aF1jV
/DGseC9U1D9pHxhPfeFPEF14dvta0KceCPhxF9i1G88Ja54m8NXE5jjS5Emj6/qlr5M8StcLcLPB
EAfXFABQAUAFABQAUAfzL0Af/9T+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFAHzL+1r/wAk
s8Kf9nNfsU/+tk/AagD6aoA+Nfj9+17pvwE+Mfw1+FWqeFbHWV+Inw0+LvxJtb0+KbzRddktvg/D
4dudd0nQdLvPCFx4Pv5TZ+JbS/1HV/FXxG8C6H4Z0yC61jxBfWWiwT6lEAec/EL9vvR/hz4W8K+I
NZ8LeGre71/9n7wX8dpNJ1bxp4psZ7j/AIS2w8S3cnhHw9N4f+FfjKzv77S5vDMtpJqXiC78LWc8
2o2BRFiW/ktAD9BpLiRLu2thZ3Usc8N1K99H9m+yWjW7W4jgud9zHdedeee7Wv2e1uYttrcfaZbY
/ZxOAfln4o/4KTeKfD/7Tb/s/Wf7Nses6NbfEKfwVqHxBj+P/wANbO6stNt9d0vRm8VzeDJ7Vmtr
S4E+tNYaRqXiTTtWudT0K50B4oNUXUY9KAPc/D/7a+neJv2p2/Zi0z4X+KU1W00C21vWNXvda8Jv
qWjQLrnxV8Pavql54Z0LWfEF1b+F9J1P4daVb3Wv6rd6NFEfHngndB53jj4e2/jEA+46APmT4C/8
lU/bX/7Ob8Kf+safsk0Aev8AxR8dWvwx+HHjj4g3cFtep4P8Mazr1vpl3qtrocetajYWUsuk+H49
WvElt7K78QaoLPRLCV4bgm+v7eOO2uZXS3cA+Lvhp+35onxG8EfFDxefCXh7w03w6/4Rn7PZ3/j/
AFXXINeOr69qOha4CPCHw48Q+JdOHhe5sYIb64g8JatZJf6hBa6pd6JbwX1/bgHD6B/wUmN78PvC
XxF1/wCCmoWWm6v8SPA/gvxhpvg/xfP47uPh1ovj3TfElzpXiLXPEsngzwp8OtbudNvrPwpaeJ9J
8CeN/GEPhm31vX7vVNUjfw1Z2viQA1db/wCClPgTSf2dde+P6eDtSuLHwj8RofBfi2xi1GHxBomk
aP8A2z4bguvFA8YfDO1+JPh9k/sfxTpy6No11dWWq+J/FdprXhbQLe+vdLkZwD7J+CvxjtPjR8KP
CfxQ0vw9qdgPEi2iXfh5TLPc6FeTajDp+qWM2p6rZeHtP1hvCsks8PiW/wDD7apo4v8ASdbsPDep
eJXsreS9APnT9rT9uCz/AGYPEWgeGLLwBZfEjVdb8MeItcayg+IOn+GNQs9W0kWUui+G3059A164
a98UWcupXumzzC1QW2jX0scN1FHNJAAfc2najp+safYatpN/Z6ppWqWdrqOmanp11BfafqOn3sEd
zZX9he20kttd2d5bSxXFrdW8skFxBJHLFI6MrMAfONh/yeT4q/7Nl8Af+rT+JdAH01QB4B+0T8dF
+AXhXw14k/4ReDxbN4l8Z2/g610268d+CfhzbR3Nx4Y8VeJIp5PE/wAQ9W0HwnBJN/wjDaZZ2mpa
1phvr/UbWC2nkuWitbgA8j8Vftm6X4V+G/gHxrceCtTutU8X/Cq9+JV7pVvF4ovdFsbuz8G614sg
8HaZ4t8OeDvE2g6pretR+FvFl3Y3F3eaPpOmeDfC2veOdf1HTtMt9MtdaAPrTw/4rsvFGieGvEWj
af4gfTPE0aTxDVtC1Hwvq2jW72N5d7/EnhzxXDoniTRLiK4tF0m60u70n+2rLVbq3gvNNggS9ubQ
A8o8U/Hq38M+OdX+HUfw/wDGWteK7f8A4Qv/AIRmx0+68HQxeN18Y6H8VfEaS6Hd3/im1t9Pi0nT
Pg146W9XxQ+gXU9/p9vb2Nrc2+oWN7cAB8Gv2iPCHxvlkl8K6Vr9no95o9x4i8Ja7rCaVFZ+MdC0
7xTrngrW77S7Wy1S+1Kxk0XxJoUkF5ba1Zac8un6toF/ZtdPeX9ppAB79QB8y/Cz/k439qn/AK6f
BH/1ALugD6aoA+XP2qP2mLP9mjwt4Z1keGbXxnr3jDWPEOi+HPC8vimDwxdavd+HPh/4u8f3cFg6
6P4i1C6nksfCc1vJNFox0fR4bh9X8R6xo2mWjTygHmPgD9uXRfHPw00Dx8/gi50ufxD8TdS+HUVh
pd94l8faXpK6VqGg6Hc6trer+BfAWtXun6leeKfEmi+C9A8IXGhRa1r3jDV9K0u2eCwm1LWNIAPp
T4QfF3T/AIwfCzwd8TdG8PeIrFPE9joc134f1HSr/StS0i71I2CahsPia08OnWNC0wXj6laeJtNh
k0zxR4dgi17wodYtdR01LsA828aftX+DPBXxV1H4Q3Xh7xFqXim1tPD5sIrCXQ0Or6r4q1jwboHh
yyt4b/VrR7XTNV1vx3oejxeIL5rbT4NTg1mC7EFvpyXd0Ae7+BPGNl498M2niSysr7TPNvtd0fUd
J1P7GdR0bX/C2v6n4W8TaLevp91fafNc6N4i0XVNMludPvrywuXtDcWV1cWssUzgHX0AfMn7OH/I
Z/ab/wCzm/F//qBfDKgD6boAKACgAoAKACgD+ZegD//V/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQ
AUAFABQB8y/ta/8AJLPCn/ZzX7FP/rZPwGoA+mqAPL/FHwY+GPjbxXD4z8W+CvDfiPWV8JXPge9O
t6Do2rWuteGZPEWj+LLDTNdg1Gxuf7VtvD/iLRk1jw1Bds9voeo6jrF7YxR3WpXErAHm8H7I/wAF
bbwjaeBrTTPFOk+F7T4U6B8GTpHhXx74y8Bade+CPDsfiZLW21TTPAGteFtL1W+u38YeIJ9Qu9Qs
7gXFxqNzIkUH2i5WcA+jpLSGS7tr1muRPaw3UESpeXkVq0d21u0xuLGKdLK7lU2sX2ee7t5p7MGd
bOSBbq6E4B8ya1+xn+z1r3xPk+M9/wCBLJvifP4w8H+Nbjxii27avPqfgTWbXX/DluZp7acQWdpq
dlaySSWi2+qXFrBHpsmpHTR9jUA6HSf2Xvg5pHjiT4hw+HZ5/Fcet6L4i0nWLjUbkaxoWtaQnixL
jUbTxJavbeK9UufEqeOPE1t4vk8U694gPibSNQi8M6qJ/C2naVotgAfQlAHzJ8Bf+Sqftr/9nN+F
P/WNP2SaAPa/H/gfQviX4M8R+APFK3k3hfxfpk2g+JrGyu5LCTWPDt+Vh1zw/PdwbbqDTvEWltda
Hqz2M1rqH9l6heLp99p960F7bgHhvhj9kX4WeENA8eeE9EvvHMXhr4iyXtz4isLnxTLe6rPqOo+J
LjxZe61N45ubR/iNrXiGbWry/nTxD4q8ZeIdas0v7qOwvrPdGUAGeOP2O/gr8RfB/jDwT4rt/HWp
aX4x1u18T3F9N8TPHc/iHRvEth4Pu/A+ma3oXiG71651W3m0zRb64ey0++uNQ0OPUnXUH0mWdEZQ
DXk/ZT+C6+FJvBen+GodP8OW+geINA8LaLdWuj+L/D/gSPxX4ftfDXiXUvCnhD4haT4v8FJquvad
bO+sz694c1621W81jxdd6ja3Mvj3x3/wkgB6r4L+Hvh/wJ4F8LfD3RG1IaH4SsdGs7CZ7+S01K6f
Rrm3vku9QuNGXSYXk1G/t/tWr2Npa2ei36XF3pj6Wui3D6awB5J8W/2U/hR8avFmn+OfHCeJrrxN
otjZ6boFxb+IJm0TR7G1XWfMt/8AhCNSg1LwDrwvpddvbu7m8XeFvEdwt7BpN3ZzWdxoWiSaeAfQ
Wjab/Y2kaXpAvr7U/wCy9Ps9P/tHVJIZtSv/ALHbx2/23UJbeC1t5L26MfnXLW9rbW5mdzDbwRbI
lAPnew/5PJ8Vf9my+AP/AFafxLoA+mqAPGfi98Bvh98a4dMPjKzum1LQrO/sNC1W3NhfDS7bVtb8
Ja9qyHw34l0/xB4G1l9Qu/BWhQPL4l8K63LZ2KX9rpj2K6pqDXABz2pfsvfCjVvC9n4Lv4PFtx4X
sNA8WeH7XSX8deKysa/EC71Gbx/rrXzaqdTm8XeMLLWdc0LUPF018/iHSvD3iHxNpPhbUfD9t4n8
QpqoB77PZw3MtlNI1yr6fdPeW4gvLy1ieZ7O7sCt5BbTww6jbCC+ndbPUI7qzS7W11BIFv7Gyubc
A8m1/wCAnwx8T+IvEPizWtN8S3PiHxPZ6BYajqUPxF+JGnyWlp4ZHiJNGi8OQ6d4ts7XweYLfxf4
ssbmXwlBos2p6b4o8R6Zqj3mn65qlvdAHR+DfhZ4C+H2oa3qfg3w/HoU+vpbRX0Ftf6pLplvb2t9
q+qR2eiaLdX1xo/hmxk1bX9b1i8sPDdhpVnqGsarf6tfwXGo3U1wwB6BQB8y/Cz/AJON/ap/66fB
H/1ALugD6aoA4T4gfDXwb8UdM07Q/HOjWviHQ9P1VtWbRdQgt7vS9Rlk0bWNCkttUsrqGaG8s3sd
cvj5JCMtwtvcRypJAhoA8q8Ifsq/CXwJ4N0PwH4XstX0jw7oHizxN47gttN1CHSn1Pxn4h1jUdcs
vE3iZtHsdNj8V6r4N1HUvtnguXxHDqcWj6npfh3xDNHfeJ/DHh/W9NAPZvDvgvw/4U8H+FvAegW9
9p/hnwZpHhjQvD1omtazJd2mleD4tOg0KzuNYm1CTWNTSKDS7O31A6nf3ja3bC4ttbOo299exXAB
x/iH4G/C7xVruo+JNd8NzXer6pPBqFxPF4h8UWFtDr9ppum6NY+MtM03TtbtNM0X4gaZpGj6TpWl
fEPR7Sx8caVpunWNjp2v21rawwqAegeHPDuj+E9E07w7oFobHSNKg8i0ga5u72c7pHmnuby/v57r
UdS1C9uZZrzUdT1K6u9S1K/uLm/1C6uby4nncA2qAPmT9nD/AJDP7Tf/AGc34v8A/UC+GVAH03QA
UAFABQAUAFAH8y9AH//W/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQB8o/toaJovib4JaX4
c8SaRpfiDw9r/wC0P+xxouu6Drdhaaro2taPqn7X/wAC7HU9J1bS76G4sdR03ULKea0vrG8gmtbu
2mlgnieJ3RgDU/4Yq/Y3/wCjTP2Z/wDwxPwu/wDmUoA85+I3wI/4JyfCGz0vUfin8Dv2Nvh7p+tX
39m6Xe+MPhR8G9AtLy7UI8wjuNS8O20SwWkckct/eSMlnp8LxzX1xbROruALffAX/gnbp2l6hrN3
+z7+ycun6VoHhLxXqEsXwP8AhjdTWvhrx7e3mneDNeks7XwhPenSfEt/p2o2ekXyW7W95cabqMUc
hewvBAAIvwI/4JxTX2saVZ/BD9jTU9X8O3Hg218QaLo3wr+DOta3oc3xDn0i38CjWNG0nw9e6npi
eLW1/RZfD817aQQ6naapZ31rJJZTJOwBHf8AwL/4J06VqQ0fU/2fv2T9O1FvFtr4ES2vvgZ8NLUv
4wvpvD1vY+H0kn8IRwvqF/c+LPDdrYxK5W8utZsba2eWeXYoB6V/wxV+xv8A9Gmfsz/+GJ+F3/zK
UAH/AAxV+xv/ANGmfsz/APhifhd/8ylAHzv8FP2RP2T9V+JX7Xtjqf7MP7POo2Xhv9ojwzovh2zv
vgv8N7u10HR5/wBk39l/xFPpOi29x4Zki0vTZvEGv67rktjYpBayaxrWram8TXuo3k8oB9Ef8MVf
sb/9Gmfsz/8Ahifhd/8AMpQAf8MVfsb/APRpn7M//hifhd/8ylAB/wAMVfsb/wDRpn7M/wD4Yn4X
f/MpQAf8MVfsb/8ARpn7M/8A4Yn4Xf8AzKUAH/DFX7G//Rpn7M//AIYn4Xf/ADKUAH/DFX7G/wD0
aZ+zP/4Yn4Xf/MpQAf8ADFX7G/8A0aZ+zP8A+GJ+F3/zKUAO/wCGLP2ONuz/AIZN/Zo27t23/hRP
wuxuxjOP+EU64OOn49qAG/8ADFX7G/8A0aZ+zP8A+GJ+F3/zKUAH/DFX7G//AEaZ+zP/AOGJ+F3/
AMylAHOar+y3+wRoWr6ToGt/s6/siaPr2vw6lcaFomq/CT4N6dq+tW+jWrX2rz6Tpt34eivNRh0q
yje81KWzt5ksbVGuLpooVLUAY8X7Pn/BOm4sINVg+CP7Fk2mXXh/WvFtrqMXw3+Bslhc+FfDd/aa
X4i8TQXiaK1vN4f0HU9QsNO1rWY5G03S7+9tLS+uYLi5gjcA3vDf7KP7CPjPRrTxH4P/AGbf2SvF
fh6/e7jsde8N/B/4Pa5o16+n3tzpt+lpqml+HLqxuXstRs7vT7tYZ3Nte2tzaTBJ4JY0AN3/AIYq
/Y3/AOjTP2Z//DE/C7/5lKAD/hir9jf/AKNM/Zn/APDE/C7/AOZSgBx/Ys/Y5Kqp/ZN/ZoKpnap+
BPwuwu45OB/wihxk8nAGffFADf8Ahir9jf8A6NM/Zn/8MT8Lv/mUoAP+GKv2N/8Ao0z9mf8A8MT8
Lv8A5lKAD/hir9jf/o0z9mf/AMMT8Lv/AJlKAD/hir9jf/o0z9mf/wAMT8Lv/mUoAP8Ahir9jf8A
6NM/Zn/8MT8Lv/mUoAP+GKv2N/8Ao0z9mf8A8MT8Lv8A5lKAD/hir9jf/o0z9mf/AMMT8Lv/AJlK
AMH9knwv4Z8EwftDeE/Bnh3QvCPhXQf2kvGFlofhnwxpGn6B4f0azPgj4cXJtdK0bSre007T7Zri
4nuGhtLaCMzTyylDJI7MAfXFABQAUAFABQAUAfzL0Af/1/7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQA
UAFABQAUAfMv7Wv/ACSzwp/2c1+xT/62T8BqAPpqgD4S/bZ/ZMu/2nvCptYLH4da5daF/wAIbqHh
/wAM+K/CWmRN4k1fQvHNlrWp6L43+Il3a+JNYh+F+p+Hft+nal4L8L+HNKvtUlu9SXVtd1nSNUfw
+gB438Vf2EPGfju98HaTptl8EYPC3h/4ZeBrK/m1D/hN4LVvit4Z0j4uJq2qaX8N7O0m0L/hGNW8
T+KPhv4lNzrXi3VdWu5vBltaa3p2qW+lhPEQBr+IP2FNY8b/ABC1T4neL9O+Ftx/wkfjj9mnxQPh
Sl34g1fwR4D0f4Y6F8O9D+I/hbTL7xD4d1PRPFOj3MHhW+l8I2Xh/wCGPwZOt3emeFLjxZfWsMd5
ZwAG7rn7F3jXUfiP4U+KFh4z8OWtz4f+Mem+LrnwbLpTw29z4UsP2oPip8Xp54fGlvDcanHfXfg3
4lJJL4O/sFNGv/GfhjQorvxDa2iDW7UA/QqLT/L1m/1Xy9MH23TNI0/zotN8rWX/ALMu9bufLv8A
WPtT/btMi/tbdpGm/Yrf+yrubW7r7Vef2z5VkAadAHzJ8Bf+Sqftr/8AZzfhT/1jT9kmgD6boAKA
CgAoAKACgAoAKACgAoA+Wvj98DfFPxs1S30VtV8NWHw6u/BXivRNXgkhv4vEieLtc0XXfD/h7xbM
1pA0PijT/Atj4h1a/wDDXhG+1LRNLi8SapceIrua61XS/DlxowBD4P8Agv8AEHwv8TtB+IE+peBN
Qlbw/wDG628VSWtrrmlumsfFjxl4P8Y6VaeHtMZdRU6B4Xk8C6daXxvNat7nxFq3iXxX4tS10S8u
jpN2Ae6fDXwavw+8AeEPBZvjq114e0HT7DVddkhEN14k14QrL4h8U6iu+V5dX8U65LqHiHWbqeae
6vdV1K8u7u4uLmeadwDt6ACgAoAKACgAoAKACgAoAKAPmT9nD/kM/tN/9nN+L/8A1AvhlQB9N0AF
ABQAUAFABQB/MvQB/9D+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFAHjXx7+Gev/ABb+HX/C
JeFfFej+CfEll4++D3xC0PxH4g8J3vjnQ7XVPhD8YPAvxas7LVvCuneL/AV/qthrc/ghNDuVs/F2
iXFnFqTahFcSvai0ugDiP+EU/bM/6L1+zH/4iR8Vf/o2aAD/AIRT9sz/AKL1+zH/AOIkfFX/AOjZ
oAP+EU/bM/6L1+zH/wCIkfFX/wCjZoAP+EU/bM/6L1+zH/4iR8Vf/o2aAD/hFP2zP+i9fsx/+Ikf
FX/6NmgA/wCEU/bM/wCi9fsx/wDiJHxV/wDo2aAD/hFP2zP+i9fsx/8AiJHxV/8Ao2aAOG8JfBP9
rHwZr/xP8R6V+0H+zvPffFnxzp/xB8Sxah+yf8SprSz1vTfhp8PPhXBbaHHbftl2k1rpbeHPhn4f
u5oL+41S7bW7rWLpL5LC5stM00A7n/hFP2zP+i9fsx/+IkfFX/6NmgA/4RT9sz/ovX7Mf/iJHxV/
+jZoAP8AhFP2zP8AovX7Mf8A4iR8Vf8A6NmgA/4RT9sz/ovX7Mf/AIiR8Vf/AKNmgA/4RT9sz/ov
X7Mf/iJHxV/+jZoAP+EU/bM/6L1+zH/4iR8Vf/o2aAD/AIRT9sz/AKL1+zH/AOIkfFX/AOjZoAP+
EU/bM/6L1+zH/wCIkfFX/wCjZoAP+EU/bM/6L1+zH/4iR8Vf/o2aAD/hFP2zP+i9fsx/+IkfFX/6
NmgA/wCEU/bM/wCi9fsx/wDiJHxV/wDo2aAD/hFP2zP+i9fsx/8AiJHxV/8Ao2aAD/hFP2zP+i9f
sx/+IkfFX/6NmgA/4RT9sz/ovX7Mf/iJHxV/+jZoAP8AhFP2zP8AovX7Mf8A4iR8Vf8A6NmgA/4R
T9sz/ovX7Mf/AIiR8Vf/AKNmgA/4RT9sz/ovX7Mf/iJHxV/+jZoAP+EU/bM/6L1+zH/4iR8Vf/o2
aAD/AIRT9sz/AKL1+zH/AOIkfFX/AOjZoAP+EU/bM/6L1+zH/wCIkfFX/wCjZoAP+EU/bM/6L1+z
H/4iR8Vf/o2aAD/hFP2zP+i9fsx/+IkfFX/6NmgA/wCEU/bM/wCi9fsx/wDiJHxV/wDo2aAOs+Bf
wv8AF3wy03x8/jrxp4c8c+KfiF8Sta+Iuq6p4T8C6n8PNAs5dW0Tw3oiaTp/h3WPH/xL1FY7aPw6
s7Xlz4puGne7ZBbQCEGUA9woAKACgAoAKACgD+ZegD//0f7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAfzL0Af/S/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQB/MvQB/9P+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQB4jofxL+Jup6rpdh
qf7OfxC8OWN7eWtvfa3qPjL4MXljo9vNIqT393baL8SdT1W5gs0LSyRadp95dyqhWC3kdgtAHt1A
H5o/thft/eKf2W/iQ3gnR/gJdfEvQrT4d+HvH2seNY/GN9oVjo41LWfHdprek3Gn2XgfxM003h7R
PB9lr9zLFebxbeI7A6hbaXZG31C/AH+Bf27/AIgeKfgV4N+KOsfAHTtB8d+LPip4X+GVx8MtN+If
ir4iRaBJ4n+DNl8aLbVj4l+Enwa+Iuq+LYW0C/sXsR4F8E+I7G607ULTV77VNIig1i30gA19Z/b4
j8G/Aj9pz4xfEb4cP4R1D9n/AFKDw5oXhSF/iu178SPFeu/D/wAL+LfB2i2Wm/Eb4IfCPxvpDa5r
fiux8PXV83gjUdC0nTrbUPFt5rkeh6dq8ulgHRfDH9rj4keKvjdcfB/xZ+zb8WtDsvJ0rR4PHY8K
x6b4XsvGejL4gj+JR1LV73xFfeHrnwJa/wBk6fqfgXxLofiLVNX8Sx6ndaKfDC3OnabqviIA8Zs/
+CofhCX9ofVvgzceFdNGnr8a9I/Z50VINc11vHT/ABBi+OPiT4L+KNb1TS5fB0fg+Pwik8fhXxDo
SWnjOXWJNKfxCb+JNRi03SJQD9R77UlsbnR7VrPUbk6zqMumpNY2M13bac0Wk6pq5vNYniBTTNOd
NKewivrjEL6tfaXpwJn1CAUAaNABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAfzL0Af//U/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQBR1S0ub/T
NRsbPU7zRbu8sbu0tdZ0+LT57/Sbm4t5IYNTsYNWstS0qa8sJXW6totT06/0+SaJEvbK6tmlgcA8
TtvhH8SILm3nl/ak+Nd7FDPFLJZ3Xhf9m1ba7jjkV3trhrP4BWd4sE6gxStaXdrciN2MFxDKEkQA
9K8P6L4r0vX/ABjd6x4zPiXw3reoadqPhPQ7vw/p+n6n4JC2C2mtaKmv6ZLbR+IvD95d29vq2jR6
roq+IdGvbzXLe98S6/pVzoWneGQD8+f2qf8Agndqf7S3xb1P4ux/G5fB19L4ItPh9ovhW4+GsPiX
wxpOjxaF4z0y/wBeuIk8aaDda3421qfx9rlnql9rEt54GvvCem+DNB1X4capqvhKz8T3QBd8N/sD
axY/C7T/AIWeI/iB8PtZ0HSPjvpHxb0jTz8ILnxDoOn+HNF+Eg+FuneArrSPiv8AEL4oT+JrfS47
fT7zw9qXinVdV/4RrStP07w3otna6RofhqDRQD0TQv2No/B3wa/ax+F/hfxH4Tt5v2ktF8VWunto
vwy8NfDfw94S1PXvgzpXwohku9D8CrBpuqp52jwa3e6hBplhqEsU7WLpcvaxXM4BxPgb9iPxl4M+
O1v8dYfiB4Hk16T4w/Hrx5qjjw58WLrV9R8JfE2H4wxeCPCmpyan8cb3wHeQ+Dz418CNqEOg/DPw
Zc3sXg1rbT9dsTNcXGqAHDp/wTw8YWvxLvvHGn/Ej4RR6he6xpfjWT4haj+zX8M9T+Iq/EHS/D/g
/Vv+EqhsTYWnhOx8S6h8ePDGsfF7VvGmmW9lr2p6T8QvGvgW7ifW4fA3xO8EgH6g3tldXVzo88Gs
ahpsWmajJe31nZQ6VJbeIbZ9I1TTl0jVm1HTNQvLfT4b3ULTX45dCutG1Y6rommQTanLoc2saRqo
BpUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQ
B//V/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQB8zftcXGrRfB6xs9H8ReJfCtx4g+OX7Kv
g691vwfr+p+F/EcGgeOP2pPg34O8UWmm69o1xaanprav4a1zVtHuprO4ikeyv7mEsY5XVgBv/DLH
hn/orX7Tf/iSPxc/+aigA/4ZY8M/9Fa/ab/8SR+Ln/zUUAH/AAyx4Z/6K1+03/4kj8XP/mooAP8A
hljwz/0Vr9pv/wASR+Ln/wA1FAB/wyx4Z/6K1+03/wCJI/Fz/wCaigA/4ZY8M/8ARWv2m/8AxJH4
uf8AzUUAH/DLHhn/AKK1+03/AOJI/Fz/AOaigA/4ZY8M/wDRWv2m/wDxJH4uf/NRQB4p8OfgnF4l
+KH7QfhPVvjF+0lLo3w48ZeCNF8LQw/tB/FO2ntbDX/hR4L8XalHd3UPiNJ9Rkk1vW9QnimvJJpI
IJI7SIpbwxooB7X/AMMseGf+itftN/8AiSPxc/8AmooAP+GWPDP/AEVr9pv/AMSR+Ln/AM1FAB/w
yx4Z/wCitftN/wDiSPxc/wDmooAP+GWPDP8A0Vr9pv8A8SR+Ln/zUUAH/DLHhn/orX7Tf/iSPxc/
+aigA/4ZY8M/9Fa/ab/8SR+Ln/zUUAH/AAyx4Z/6K1+03/4kj8XP/mooAP8Ahljwz/0Vr9pv/wAS
R+Ln/wA1FAB/wyx4Z/6K1+03/wCJI/Fz/wCaigDxL9mj4JRfE/8AZx/Z/wDiX4v+Mf7Sd54s+Ifw
S+FPjnxRd2n7QvxT061uvEXi3wJoOv61cW2n2XiOGzsLefUtQuZYbK0hitrWNlggiSJERQD23/hl
jwz/ANFa/ab/APEkfi5/81FAB/wyx4Z/6K1+03/4kj8XP/mooAP+GWPDP/RWv2m//Ekfi5/81FAH
imhfBGK//aM+KXw1ufjF+0m3hTwr8FPgL450a1X9oX4qJdweIfH/AI6/aQ0DxNcS6gviQXdzb3Wm
/DXwnHb2c8r21jJZ3U9pHFLqF68oB7X/AMMseGf+itftN/8AiSPxc/8AmooAP+GWPDP/AEVr9pv/
AMSR+Ln/AM1FAB/wyx4Z/wCitftN/wDiSPxc/wDmooAP+GWPDP8A0Vr9pv8A8SR+Ln/zUUAeJ/Cr
4IxeLfHf7S2ga18Yv2k59N+GHxs0HwN4Rjh/aF+KdrJaeHtQ/Zy+AHxKube7ng8Rxy6jcN4s+Ifi
e7W8vWmuUtbq109JRZ2NpDEAe2f8MseGf+itftN/+JI/Fz/5qKAD/hljwz/0Vr9pv/xJH4uf/NRQ
Af8ADLHhn/orX7Tf/iSPxc/+aigCt+y4mqafa/HHwvf+KfGHi2y8F/H3xV4Y8P3/AI48T6x4w120
0KDwh4C1K3019d126vNSuba3vdUv5oEnuHEX2iRUwu2gD6koAKACgAoAKACgD+ZegD//1v7q/gp/
yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAfMv7Wv/ACSzwp/2c1+xT/62T8BqAPpqgAoAKAPwj/b8
8B/tB+Nf2pbPXvA/hL463Xw90nwp4A8HXGpeDfB+t6t4Vur3w/r8ni/W5bay0b/hLbrVYv7I+JFy
2sa/ceFNLsdd1PwnpfgLSYtUuvDnifU9PAPW7vwn8etV8bfCbWrXwt8YjYWl5+w9caheWl3P4K0b
S9PsNe+G138Ube/8C3nwqvdRtLax05Nf/wCE40ew8X+DbaxtP7R0vVtKtDa3y3YB+wNABQAUAfMn
wb/5Lp+19/2Uf4Xf+qC+GtAH03QAUAFAH5df8FEvDvxg8Zt4f8K/DK4+KdlZan4E8aWep6j8O/Dn
x4vNIt9Z1dY9L0vTvHN98JfGujpqmj6rocvivUNEg07wnruseGPHHhrwjH4sv7bwB471LTdUAPJ/
jn4V+N3xG0z4S6vp/wAPfitrXhzxloXwZ0+bwr4gt/GfiHxh4dvPBX/Cyr74ian4i+FvxP0bxV8O
PAusRafqngA6z4y8S+P9G8a/EC58Kan4B0DWvG+keO9UfxCAfqb8EY9Si+DHwjj1m3+yayvwy8Bj
WLX/AIRo+DDb6qfC2lnUYT4QbRPDLeFWjvTOreHH8OeH30RgdNfRNKa2NhbgHqFABQAUAfMf7E//
ACZn+yP/ANmx/AT/ANVV4UoA+NP+Ci/wW+LXxQ8cfDWb4e+JPF+jWL+BfG+k6lH4bf8AaFbSr/Tl
utPj8ReCvGUPwRi1y3m8GfEZ9c8KP4o0PU/CcWveK9O8AfZvDXxK+HE+kTjxSAeC/tG+Bv2tbsfs
q3fw2k/az12Twt8P/AeveOv+EF1zWLKwvp30r4k3H9m61p3xP+K8PiPRfic+g3d/o/jDxbdfET4u
+IodYv8AwvFeeCbuysNC0PxSAftX8NBcL8OPh+t3/wAJR9qHgnwoLn/hN57i68afaBoVgJv+Euur
uw0q7ufFHmbv7fnudM024m1X7XJNYWcjNbxAHjfhb/k8n46f9my/so/+rT/bNoA+Hv2j/hn8fde/
bA+CXjrQ/FX7S/hbwEniTX/CcGkeDfFHhzWtO1PUbjxT8Kp9P8R6z4N0fS7jwl4X+Bnh2y0268Xa
nc+NNa1Lxx4u1bwwINd8HDSLFtI8bAHoum3Pxq0j9sU6rqXij4w638OtQufiPb3txaeAPiVB4I0l
bzxP8N9N8J+EdM0HUv2XfE1lYaRb6J4XS31PXNF+N8WgeKNQg8WfFPTfEPgyPxbceFlAPDvg9ZfH
vTv2pZvE2s6f8fdR8M+KY/ip4QtrPxH4a/ag8OeB9HlTR4G+HniLT73xB4y+IegeBfht4s8OaPoB
SDV9H1zx14P+Kmo+J/7U8PafbW2iajQBa/Ya+Dv7Rngr47+FfEHj/wAL+K9P8IRfsxfByC/1rULe
x03RbnxB4q8I3/8Awl1jq2heL9U1T4owfEDSvEPgXwno2p3V3r6RaFp+nb5/hH4Jv/iV4j1y6AP0
C+Av/JVP21/+zm/Cn/rGn7JNAHzH+3v8Gfjb8X/EfhWw+Heranp3hCz+GPibUddGi3HipNS/trw7
8YPgZ4jiWH7FBqnhtDd6BY6sl1pNv4e1D4i+MvDlv4n0Twdq+m2Vt4g8J/EMA8vt/Cf7T9l8CPg7
4ciOrf8ACY+Hf2W43mt7n4afF7xPqPhbxjq114Yk+FWlWvib/hIvAFpf/GvUPHXh7QNV8U654p8C
6no3wT0XwTrFx4x0fwl4d8XG/wDHwB+uOg2+s2eh6PaeItUs9b1+10uwt9b1nTtKfQrDVtXhtYo9
R1Oy0STUtYk0e0vrtZrq30x9X1RrCKVbU6heGH7Q4B89fs4f8hn9pv8A7Ob8X/8AqBfDKgD6boAK
ACgAoAKACgD+ZegD/9f+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFAHyj+2jqF3pPwS0vVLD
Q9U8TX2m/tD/ALHF/Z+G9Dl0WDWtfurT9r/4Fz2+i6RP4k1jw94dh1PVJY0srGXXtf0TR47qeJ9T
1bTrNZ7yIA0/+F9fFT/oyj9pv/wqv2NP/ouaAD/hfXxU/wCjKP2m/wDwqv2NP/ouaAD/AIX18VP+
jKP2m/8Awqv2NP8A6LmgA/4X18VP+jKP2m//AAqv2NP/AKLmgA/4X18VP+jKP2m//Cq/Y0/+i5oA
P+F9fFT/AKMo/ab/APCq/Y0/+i5oAP8AhfXxU/6Mo/ab/wDCq/Y0/wDouaAD/hfXxU/6Mo/ab/8A
Cq/Y0/8AouaAPnn4UfGn4k2vxk/alvYP2Rf2htSudU8f/Dqa+0my8S/snpqHhyS2+CXw9s4bTWZN
R/af0/SprjULeCLVrRvD2qa9aJp95bR391Zaot3ploAfQ3/C+vip/wBGUftN/wDhVfsaf/Rc0AH/
AAvr4qf9GUftN/8AhVfsaf8A0XNAB/wvr4qf9GUftN/+FV+xp/8ARc0AH/C+vip/0ZR+03/4VX7G
n/0XNAB/wvr4qf8ARlH7Tf8A4VX7Gn/0XNAB/wAL6+Kn/RlH7Tf/AIVX7Gn/ANFzQAf8L6+Kn/Rl
H7Tf/hVfsaf/AEXNAB/wvr4qf9GUftN/+FV+xp/9FzQAf8L6+Kn/AEZR+03/AOFV+xp/9FzQB87f
sg/Gv4laV+yZ+y9pdj+yF+0R4lsdN/Z2+ClhZ+I9E8S/smwaNr9rZ/DXwzb2+t6RB4j/AGotA8Qw
6ZqsMaX9hFr2haJrMdrPEmqaRpt8txZQAH0T/wAL6+Kn/RlH7Tf/AIVX7Gn/ANFzQAf8L6+Kn/Rl
H7Tf/hVfsaf/AEXNAB/wvr4qf9GUftN/+FV+xp/9FzQB88eG/jX8So/2sPjNqifshftET3t3+zx+
zNYT+HIvEv7Jo1nTLXT/AIk/ta3FprV9PN+1FD4ek0zXZtTvbHSotN13UdZhuvDusPrekaNYz+H7
3XgD6H/4X18VP+jKP2m//Cq/Y0/+i5oAP+F9fFT/AKMo/ab/APCq/Y0/+i5oAP8AhfXxU/6Mo/ab
/wDCq/Y0/wDouaAD/hfXxU/6Mo/ab/8ACq/Y0/8AouaAPnf4KfGv4lWfxK/a9uLf9kL9ojVZtV/a
I8NX99Y2HiX9k2O68NXUf7Jv7L+lpomtvqn7UWm2M+pz2Om2fiOKXw5eeINGGja/pME+rweIYdd0
HRQD6I/4X18VP+jKP2m//Cq/Y0/+i5oAP+F9fFT/AKMo/ab/APCq/Y0/+i5oAP8AhfXxU/6Mo/ab
/wDCq/Y0/wDouaAML9knV9Q1+D9oXWtV8La94I1LUf2kvGE954S8T3Hhi78QaDKPBHw4iFlq1z4L
8R+L/Cs1y0caXIfQ/E2s2fkXEKm7FytxBAAfXFABQAUAFABQAUAfzL0Af//Q/ur+Cn/JGvhJ/wBk
y8B/+orpVAHptABQAUAFABQB8y/ta/8AJLPCn/ZzX7FP/rZPwGoA9O1z4o6N4Z8e2ngrxDZ3Oh2F
18PPFfxGHjrVtQ8P2Pg+HTfBmueEdE8QafdXM+srqtje6efGuh3891qWlWWjNZXB+y6ndXMF7b2g
BzvhD49+C/iDq3wxh8Di48U+Fvix8O/EvxF8MePtHvvD954X+x+Gb3wfZ3WhXYg1mTW49fk/4TG2
laFNIksLJtO1Gxv9Qt9SiSyYA6fwZ4x8QeI/E/xE0LVvDmmabp/gvW7HSdN17R/EN5rVrrMl9aSa
q1heW2o+GvDdxpmuaZoVz4a1TWINP/4SDw/bz+JU0Ww8T6pqeha5HaAHo9ABQAUAFABQB8u/CS6t
rH41/tjXt7cQWdnZ/ED4aXV3d3U0dvbWttb/ALP3w3lnuLieVkihggiRpZppXSOONWd2VQxoA820
v9vz4VaqPge8Oh+ILb/hd2seINEsNNv7/wAK2niTwxe6T46+E/gqxXXNBl18SzHU7P4zeC/H89vp
lxd32lfDye58QXNpLMtvp92AfTvwp+I138UfDNh4wHgnxF4R0DxBpGheJfCd14gvfDVxNr3h3xJp
66npt09loWuatd6PqMVo8Euo6XqcMItlvbNLa9vrgajb6WAenUAFABQAUAFABQAUAfMf7E//ACZn
+yP/ANmx/AT/ANVV4UoA+nKAPF/hD8dPB3xnu/iLZ+F1u7ef4ceONW8G30eoS6a0ms2umXl3plt4
z0VNPv74zeD9f1fSPEem+H9Uufs76nP4b1d44FjgVmAPaKAPmXwt/wAnk/HT/s2X9lH/ANWn+2bQ
B9NUAeW/Gb4p6V8F/h9qHxB1q1W80+x13wP4faKTU9P0W2S68eeOvDfgLTbq+1bVZYrDTtNsdS8T
Wl7qd3Ox8nT7e5eKKaYRQuAbvw28daV8UPh74H+JGh2uo2GjePfCXh7xhplhrEdpDrFhY+ItKtdW
trHVobC81Gyg1Syiu1ttRgtL+9t4byKaKG6uEVZWAO1oA+ZPgL/yVT9tf/s5vwp/6xp+yTQB9N0A
eP8Awl+Ltj8VR4uEGlP4fuvCviTU9EfR9RvlPiGTTrPV9Y0jTvEOoaK9pa3Wk6b4hk0S/uNDmY3l
pfw291HBfSXWn6hb2oB7BQB8yfs4f8hn9pv/ALOb8X/+oF8MqAPpugAoAKACgAoAKAP5l6AP/9H+
6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFAHzL+1r/wAks8Kf9nNfsU/+tk/AagD2S5+Hnhe7
8f6V8TriHWn8YaJ4d1nwppdyPFni1NFtdC8QXekX2tWg8IR62ng+WbUbzQNEuLnUZ9Cl1NpNJ08i
8H2SAIAUn+Ffgc+JvBXi6DTL/TtW+Hfh/UPCvg620bxJ4n0Pw3o/h7VItPhvdJ/4QzRtZsPB2oWj
xaTpSQrquhXzWi6Xpv2QwfYLQxAHdW9pDavdvE1yzXt0bub7ReXl2qzGGC3K2yXU8yWVuI7eMizs
lt7NZTLOsAnuLiWUAs0AFABQAUAFAHyR4C8N6J4y+KH7b3hDxNYJqvhzxV4s8B+HPEGlyS3EEepa
Jrf7Onw80zVbCSa0lguoo7yxuZ7eSS3nhmVJCYpY3CuoB6Je/s1/BK98T2Pi8+Bbew1mx1OTWVTQ
ta8S+HNCvdSmm+HlxLda14U0DWdN8K+IWkn+E3w4lePXdG1GFpPB+jMY8wMZQDt/Anw08HfDWyn0
7wdYahp1hNFYWsNnfeI/E3iG20vTNJhkt9I0Hw/F4j1jV08N+GNGhmmi0bwt4fXTPDukJPOum6Zb
iaUsAd5QAUAFABQAUAFABQB8x/sT/wDJmf7I/wD2bH8BP/VVeFKAPpwjII5544JB/AjkH3HI7UAe
ceBvhF8Nfhm0L+AvB+k+FXi8KeGvBDNpCTwG78M+DjqJ8MafqZMz/wBrS6KdY1Y2ep6n9r1VTqmo
b75/ttxvAPR6APmXwt/yeT8dP+zZf2Uf/Vp/tm0AfTVAHKeNfBXhz4heHpvC/iq1vLvR5tS8P6xs
07Wtc8Oahb6r4V8Q6V4r8PajYa34b1HSdb0280nxDoul6pa3Gn6hbSie0jR2aFpY3AL3hnwzofg7
QdM8M+G7FdN0XR7f7NY2onuruUKXeae4u76+mudQ1LUb25lmvdS1TUrq71LVNQuLnUNRu7q9ubi4
lAN2gD5k+Av/ACVT9tf/ALOb8Kf+safsk0AfTdAHGeF/h94V8Hajr+r6FZXyan4nmgfV7/VNf8Q+
Ibt7a0vNX1DT9HsJ/EWq6tJovhvSb3XtcudF8LaKdP8ADeiSavqR0nTLT7bcbwDs6APmT9nD/kM/
tN/9nN+L/wD1AvhlQB9N0AFABQAUAFABQB/MvQB//9L+6v4Kf8ka+En/AGTLwH/6iulUAem0AFAB
QAUAFAHI+O/AHgf4oeF7/wAE/Efwl4d8c+D9VuNJutS8MeKtIstd0K/udB1nT/EOiT3emahDcWlx
LpOvaVpmsafJLEzWmpafaXkJSe3jdQDxL/hiz9kT/o2j4Hf+Gz8J/wDytoAP+GLP2RP+jaPgd/4b
Pwn/APK2gA/4Ys/ZE/6No+B3/hs/Cf8A8raAD/hiz9kT/o2j4Hf+Gz8J/wDytoAP+GLP2RP+jaPg
d/4bPwn/APK2gA/4Ys/ZE/6No+B3/hs/Cf8A8raAD/hiz9kT/o2j4Hf+Gz8J/wDytoAP+GLP2RP+
jaPgd/4bPwn/APK2gBB+xX+yGM4/Zm+BgydzEfDHwiCzbVXcxGmZY7UVQWyQqhRwAFAF/wCGLP2R
P+jaPgd/4bPwn/8AK2gA/wCGLP2RP+jaPgd/4bPwn/8AK2gA/wCGLP2RP+jaPgd/4bPwn/8AK2gA
/wCGLP2RP+jaPgd/4bPwn/8AK2gA/wCGLP2RP+jaPgd/4bPwn/8AK2gA/wCGLP2RP+jaPgd/4bPw
n/8AK2gA/wCGLP2RP+jaPgd/4bPwn/8AK2gA/wCGLP2RP+jaPgd/4bPwn/8AK2gA/wCGLP2RP+ja
Pgd/4bPwn/8AK2gBqfsU/sgxoscf7MvwLjjRVRI4/hh4RjjjRRhUjjTTFREVQFVFVVVQAoAGKAHf
8MWfsif9G0fA7/w2fhP/AOVtAB/wxZ+yJ/0bR8Dv/DZ+E/8A5W0AH/DFn7In/RtHwO/8Nn4T/wDl
bQA0fsU/shBmcfsy/AsO6ojyD4YeEQ7pGZDGjP8A2ZvZIzLKyKSVQyyFQC7lgB3/AAxZ+yJ/0bR8
Dv8Aw2fhP/5W0AH/AAxZ+yJ/0bR8Dv8Aw2fhP/5W0AH/AAxZ+yJ/0bR8Dv8Aw2fhP/5W0AH/AAxZ
+yJ/0bR8Dv8Aw2fhP/5W0ANX9in9kFS7L+zL8C1aRg8jL8MPCKtI4RYw8hGmAu4jRIwzlmEaRpkI
iKoA7/hiz9kT/o2j4Hf+Gz8J/wDytoAP+GLP2RP+jaPgd/4bPwn/APK2gA/4Ys/ZE/6No+B3/hs/
Cf8A8raAPYfh98MPhz8JtEn8NfDDwN4U+H/h661O51q50XwdoOm+HtLuNXvYba3u9TnstLt7eCW/
uYLK0hnu3Rp5IrW3jdykSBQDuqACgAoAKACgAoA/mXoA/9P+6v4Kf8ka+En/AGTLwH/6iulUAem0
AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFAH8y9AH/1P7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFAB
QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAfzL0Af/V/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUA
FABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/
MvQB/9b+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/1/7q/gp/
yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/Q/ur+Cn/JGvhJ/wBky8B/
+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9H+6v4Kf8ka+En/AGTLwH/6iulUAem0AFAB
QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFAH8y9AH/0v7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUA
FABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAfzL0Af/T/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB
/9T+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/1f7q/gp/yRr4
Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/W/ur+Cn/JGvhJ/wBky8B/+orp
VAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9f+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUA
FABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAFABQAUAFAH8y9AH/0P7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAfzL0Af/R/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9L+
6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/0/7q/gp/yRr4Sf8A
ZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/U/ur+Cn/JGvhJ/wBky8B/+orpVAHp
tABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAFABQAUAFABQAUAFABQB/MvQB/9X+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAFABQAUAFAH8y9AH/1v7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUA
fzL0Af/X/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9D+6v4K
f8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/0f7q/gp/yRr4Sf8AZMvA
f/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/S/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQ
AUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAFABQAUAFABQAUAFABQB/MvQB/9P+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUA
FABQAUAFAH8y9AH/1P7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0
Af/V/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9b+6v4Kf8ka
+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/1/7q/gp/yRr4Sf8AZMvAf/qK
6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/Q/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAF
ABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUA
FABQAUAFABQAUAFABQB/MvQB/9H+6v4Kf8ka+En/AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQA
UAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQ
AUAFAH8y9AH/0v7q/gp/yRr4Sf8AZMvAf/qK6VQB6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFA
BQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/T
/ur+Cn/JGvhJ/wBky8B/+orpVAHptABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAU
AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB/MvQB/9T+6v4Kf8ka+En/
AGTLwH/6iulUAem0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAB
QAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAH8y9AH/1f7q/gp/yRr4Sf8AZMvAf/qK6VQB
6bQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUA
FABQAUAFABQAUAFABQAUAFABQAUAfzL0Af/W/th+DHxn+D0Pwe+FEUvxX+GsUsXw18CxyRyeO/Cy
SRyJ4X0tXR0bUgyOjAqysNysCDgg0Aelf8Lr+Df/AEVr4Zf+F74V/wDllQAf8Lr+Df8A0Vr4Zf8A
he+Ff/llQAf8Lr+Df/RWvhl/4XvhX/5ZUAH/AAuv4N/9Fa+GX/he+Ff/AJZUAH/C6/g3/wBFa+GX
/he+Ff8A5ZUAH/C6/g3/ANFa+GX/AIXvhX/5ZUAH/C6/g3/0Vr4Zf+F74V/+WVAB/wALr+Df/RWv
hl/4XvhX/wCWVAB/wuv4N/8ARWvhl/4XvhX/AOWVAB/wuv4N/wDRWvhl/wCF74V/+WVAB/wuv4N/
9Fa+GX/he+Ff/llQAf8AC6/g3/0Vr4Zf+F74V/8AllQAf8Lr+Df/AEVr4Zf+F74V/wDllQAf8Lr+
Df8A0Vr4Zf8Ahe+Ff/llQAf8Lr+Df/RWvhl/4XvhX/5ZUAH/AAuv4N/9Fa+GX/he+Ff/AJZUAH/C
6/g3/wBFa+GX/he+Ff8A5ZUAH/C6/g3/ANFa+GX/AIXvhX/5ZUAH/C6/g3/0Vr4Zf+F74V/+WVAB
/wALr+Df/RWvhl/4XvhX/wCWVAB/wuv4N/8ARWvhl/4XvhX/AOWVAB/wuv4N/wDRWvhl/wCF74V/
+WVAB/wuv4N/9Fa+GX/he+Ff/llQAf8AC6/g3/0Vr4Zf+F74V/8AllQAf8Lr+Df/AEVr4Zf+F74V
/wDllQAf8Lr+Df8A0Vr4Zf8Ahe+Ff/llQAf8Lr+Df/RWvhl/4XvhX/5ZUAH/AAuv4N/9Fa+GX/he
+Ff/AJZUAH/C6/g3/wBFa+GX/he+Ff8A5ZUAH/C6/g3/ANFa+GX/AIXvhX/5ZUAH/C6/g3/0Vr4Z
f+F74V/+WVAB/wALr+Df/RWvhl/4XvhX/wCWVAB/wuv4N/8ARWvhl/4XvhX/AOWVAB/wuv4N/wDR
Wvhl/wCF74V/+WVAB/wuv4N/9Fa+GX/he+Ff/llQAf8AC6/g3/0Vr4Zf+F74V/8AllQAf8Lr+Df/
AEVr4Zf+F74V/wDllQAf8Lr+Df8A0Vr4Zf8Ahe+Ff/llQAf8Lr+Df/RWvhl/4XvhX/5ZUAH/AAuv
4N/9Fa+GX/he+Ff/AJZUAH/C6/g3/wBFa+GX/he+Ff8A5ZUAH/C6/g3/ANFa+GX/AIXvhX/5ZUAH
/C6/g3/0Vr4Zf+F74V/+WVAB/wALr+Df/RWvhl/4XvhX/wCWVAH813/Cy/hz/wBFA8E/+FVoP/yd
QB//2Q==</pkg:binaryData></pkg:part><pkg:part pkg:name="/word/settings.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"><pkg:xmlData><w:settings mc:Ignorable="w14 w15" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:sl="http://schemas.openxmlformats.org/schemaLibrary/2006/main"><w:zoom w:percent="100"/><w:bordersDoNotSurroundHeader/><w:bordersDoNotSurroundFooter/><w:proofState w:spelling="clean" w:grammar="clean"/><w:defaultTabStop w:val="420"/><w:drawingGridVerticalSpacing w:val="200"/><w:displayHorizontalDrawingGridEvery w:val="0"/><w:displayVerticalDrawingGridEvery w:val="2"/><w:characterSpacingControl w:val="compressPunctuation"/><w:savePreviewPicture/><w:compat><w:spaceForUL/><w:balanceSingleByteDoubleByteWidth/><w:doNotLeaveBackslashAlone/><w:ulTrailSpace/><w:doNotExpandShiftReturn/><w:adjustLineHeightInTable/><w:useFELayout/><w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/><w:compatSetting w:name="overrideTableStyleFontSizeAndJustification" w:uri="http://schemas.microsoft.com/office/word" w:val="1"/><w:compatSetting w:name="enableOpenTypeFeatures" w:uri="http://schemas.microsoft.com/office/word" w:val="1"/><w:compatSetting w:name="doNotFlipMirrorIndents" w:uri="http://schemas.microsoft.com/office/word" w:val="1"/><w:compatSetting w:name="differentiateMultirowTableHeaders" w:uri="http://schemas.microsoft.com/office/word" w:val="1"/></w:compat><w:rsids><w:rsidRoot w:val="009B43C1"/><w:rsid w:val="000335F9"/><w:rsid w:val="00141166"/><w:rsid w:val="001D0C16"/><w:rsid w:val="00335E9E"/><w:rsid w:val="00407E30"/><w:rsid w:val="004554AC"/><w:rsid w:val="006F0372"/><w:rsid w:val="008727E1"/><w:rsid w:val="009026B1"/><w:rsid w:val="00987D4F"/><w:rsid w:val="009B43C1"/><w:rsid w:val="00AA2C51"/><w:rsid w:val="00B76371"/><w:rsid w:val="00CF39F1"/><w:rsid w:val="00FD57A8"/></w:rsids><m:mathPr><m:mathFont m:val="Cambria Math"/><m:brkBin m:val="before"/><m:brkBinSub m:val="--"/><m:smallFrac m:val="0"/><m:dispDef/><m:lMargin m:val="0"/><m:rMargin m:val="0"/><m:defJc m:val="centerGroup"/><m:wrapIndent m:val="1440"/><m:intLim m:val="subSup"/><m:naryLim m:val="undOvr"/></m:mathPr><w:themeFontLang w:val="en-US" w:eastAsia="zh-CN"/><w:clrSchemeMapping w:bg1="light1" w:t1="dark1" w:bg2="light2" w:t2="dark2" w:accent1="accent1" w:accent2="accent2" w:accent3="accent3" w:accent4="accent4" w:accent5="accent5" w:accent6="accent6" w:hyperlink="hyperlink" w:followedHyperlink="followedHyperlink"/><w:decimalSymbol w:val="."/><w:listSeparator w:val=","/><w14:docId w14:val="76E2D129"/><w15:chartTrackingRefBased/><w15:docId w15:val="{FFFFF82B-A1D2-465B-82CE-BF2A1CA965C2}"/></w:settings></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/fontTable.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"><pkg:xmlData><w:fonts mc:Ignorable="w14 w15" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"><w:font w:name="DengXian"><w:panose1 w:val="02010600030101010101"/><w:charset w:val="86"/><w:family w:val="script"/><w:pitch w:val="variable"/><w:sig w:usb0="A00002BF" w:usb1="38CF7CFA" w:usb2="00000016" w:usb3="00000000" w:csb0="0004000F" w:csb1="00000000"/></w:font><w:font w:name="Times New Roman"><w:panose1 w:val="02020603050405020304"/><w:charset w:val="00"/><w:family w:val="roman"/><w:pitch w:val="variable"/><w:sig w:usb0="E0002AEF" w:usb1="C0007841" w:usb2="00000009" w:usb3="00000000" w:csb0="000001FF" w:csb1="00000000"/></w:font><w:font w:name="Arial"><w:panose1 w:val="020B0604020202020204"/><w:charset w:val="00"/><w:family w:val="swiss"/><w:pitch w:val="variable"/><w:sig w:usb0="E0002AFF" w:usb1="C0007843" w:usb2="00000009" w:usb3="00000000" w:csb0="000001FF" w:csb1="00000000"/></w:font><w:font w:name="DengXian Light"><w:panose1 w:val="02010600030101010101"/><w:charset w:val="86"/><w:family w:val="script"/><w:pitch w:val="variable"/><w:sig w:usb0="A00002BF" w:usb1="38CF7CFA" w:usb2="00000016" w:usb3="00000000" w:csb0="0004000F" w:csb1="00000000"/></w:font></w:fonts></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/webSettings.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.webSettings+xml"><pkg:xmlData><w:webSettings mc:Ignorable="w14 w15" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"><w:divs><w:div w:id="320349409"><w:bodyDiv w:val="1"/><w:marLeft w:val="0"/><w:marRight w:val="0"/><w:marTop w:val="0"/><w:marBottom w:val="0"/><w:divBdr><w:top w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:bottom w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/></w:divBdr></w:div></w:divs><w:allowPNG/><w:doNotSaveAsSingleFile/><w:pixelsPerInch w:val="96"/></w:webSettings></pkg:xmlData></pkg:part><pkg:part pkg:name="/docProps/core.xml" pkg:contentType="application/vnd.openxmlformats-package.core-properties+xml" pkg:padding="256"><pkg:xmlData><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title/><dc:subject/><dc:creator>Microsoft Office 用户</dc:creator><cp:keywords/><dc:description/><cp:lastModifiedBy>Microsoft Office 用户</cp:lastModifiedBy><cp:revision>2</cp:revision><dcterms:created xsi:type="dcterms:W3CDTF">2017-12-14T08:13:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2017-12-14T08:13:00Z</dcterms:modified></cp:coreProperties></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/styles.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"><pkg:xmlData><w:styles mc:Ignorable="w14 w15" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:asciiTheme="minorHAnsi" w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorHAnsi" w:cstheme="minorBidi"/><w:kern w:val="2"/><w:sz w:val="24"/><w:szCs w:val="24"/><w:lang w:val="en-US" w:eastAsia="zh-CN" w:bidi="ar-SA"/></w:rPr></w:rPrDefault><w:pPrDefault/></w:docDefaults><w:latentStyles w:defLockedState="0" w:defUIPriority="99" w:defSemiHidden="0" w:defUnhideWhenUsed="0" w:defQFormat="0" w:count="382"><w:lsdException w:name="Normal" w:uiPriority="0" w:qFormat="1"/><w:lsdException w:name="heading 1" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 2" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 3" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 4" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 5" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 6" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 7" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 8" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="heading 9" w:semiHidden="1" w:uiPriority="9" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="index 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 6" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 7" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 8" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index 9" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 1" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 2" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 3" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 4" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 5" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 6" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 7" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 8" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="toc 9" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1"/><w:lsdException w:name="Normal Indent" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="footnote text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="annotation text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="header" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="footer" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="index heading" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="caption" w:semiHidden="1" w:uiPriority="35" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="table of figures" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="envelope address" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="envelope return" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="footnote reference" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="annotation reference" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="line number" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="page number" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="endnote reference" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="endnote text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="table of authorities" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="macro" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="toa heading" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Bullet" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Number" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Bullet 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Bullet 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Bullet 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Bullet 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Number 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Number 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Number 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Number 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Title" w:uiPriority="10" w:qFormat="1"/><w:lsdException w:name="Closing" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Signature" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Default Paragraph Font" w:semiHidden="1" w:uiPriority="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text Indent" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Continue" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Continue 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Continue 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Continue 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="List Continue 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Message Header" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Subtitle" w:uiPriority="11" w:qFormat="1"/><w:lsdException w:name="Salutation" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Date" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text First Indent" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text First Indent 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Heading" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text Indent 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Body Text Indent 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Block Text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Hyperlink" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="FollowedHyperlink" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Strong" w:uiPriority="22" w:qFormat="1"/><w:lsdException w:name="Emphasis" w:uiPriority="20" w:qFormat="1"/><w:lsdException w:name="Document Map" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Plain Text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="E-mail Signature" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Top of Form" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Bottom of Form" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Normal (Web)" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Acronym" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Address" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Cite" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Code" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Definition" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Keyboard" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Preformatted" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Sample" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Typewriter" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="HTML Variable" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Normal Table" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="annotation subject" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="No List" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Outline List 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Outline List 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Outline List 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Simple 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Simple 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Simple 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Classic 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Classic 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Classic 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Classic 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Colorful 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Colorful 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Colorful 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Columns 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Columns 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Columns 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Columns 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Columns 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 6" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 7" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid 8" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 6" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 7" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table List 8" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table 3D effects 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table 3D effects 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table 3D effects 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Contemporary" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Elegant" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Professional" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Subtle 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Subtle 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Web 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Web 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Web 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Balloon Text" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Table Grid" w:uiPriority="39"/><w:lsdException w:name="Table Theme" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 1" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 2" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 3" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 4" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 5" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 6" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 7" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 8" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Note Level 9" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Placeholder Text" w:semiHidden="1"/><w:lsdException w:name="No Spacing" w:uiPriority="1" w:qFormat="1"/><w:lsdException w:name="Light Shading" w:uiPriority="60"/><w:lsdException w:name="Light List" w:uiPriority="61"/><w:lsdException w:name="Light Grid" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2" w:uiPriority="64"/><w:lsdException w:name="Medium List 1" w:uiPriority="65"/><w:lsdException w:name="Medium List 2" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3" w:uiPriority="69"/><w:lsdException w:name="Dark List" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading" w:uiPriority="71"/><w:lsdException w:name="Colorful List" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 1" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 1" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 1" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 1" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 1" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 1" w:uiPriority="65"/><w:lsdException w:name="Revision" w:semiHidden="1"/><w:lsdException w:name="List Paragraph" w:uiPriority="34" w:qFormat="1"/><w:lsdException w:name="Quote" w:uiPriority="29" w:qFormat="1"/><w:lsdException w:name="Intense Quote" w:uiPriority="30" w:qFormat="1"/><w:lsdException w:name="Medium List 2 Accent 1" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 1" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 1" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 1" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 1" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 1" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 1" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 1" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 2" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 2" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 2" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 2" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 2" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 2" w:uiPriority="65"/><w:lsdException w:name="Medium List 2 Accent 2" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 2" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 2" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 2" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 2" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 2" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 2" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 2" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 3" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 3" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 3" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 3" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 3" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 3" w:uiPriority="65"/><w:lsdException w:name="Medium List 2 Accent 3" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 3" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 3" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 3" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 3" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 3" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 3" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 3" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 4" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 4" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 4" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 4" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 4" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 4" w:uiPriority="65"/><w:lsdException w:name="Medium List 2 Accent 4" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 4" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 4" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 4" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 4" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 4" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 4" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 4" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 5" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 5" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 5" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 5" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 5" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 5" w:uiPriority="65"/><w:lsdException w:name="Medium List 2 Accent 5" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 5" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 5" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 5" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 5" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 5" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 5" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 5" w:uiPriority="73"/><w:lsdException w:name="Light Shading Accent 6" w:uiPriority="60"/><w:lsdException w:name="Light List Accent 6" w:uiPriority="61"/><w:lsdException w:name="Light Grid Accent 6" w:uiPriority="62"/><w:lsdException w:name="Medium Shading 1 Accent 6" w:uiPriority="63"/><w:lsdException w:name="Medium Shading 2 Accent 6" w:uiPriority="64"/><w:lsdException w:name="Medium List 1 Accent 6" w:uiPriority="65"/><w:lsdException w:name="Medium List 2 Accent 6" w:uiPriority="66"/><w:lsdException w:name="Medium Grid 1 Accent 6" w:uiPriority="67"/><w:lsdException w:name="Medium Grid 2 Accent 6" w:uiPriority="68"/><w:lsdException w:name="Medium Grid 3 Accent 6" w:uiPriority="69"/><w:lsdException w:name="Dark List Accent 6" w:uiPriority="70"/><w:lsdException w:name="Colorful Shading Accent 6" w:uiPriority="71"/><w:lsdException w:name="Colorful List Accent 6" w:uiPriority="72"/><w:lsdException w:name="Colorful Grid Accent 6" w:uiPriority="73"/><w:lsdException w:name="Subtle Emphasis" w:uiPriority="19" w:qFormat="1"/><w:lsdException w:name="Intense Emphasis" w:uiPriority="21" w:qFormat="1"/><w:lsdException w:name="Subtle Reference" w:uiPriority="31" w:qFormat="1"/><w:lsdException w:name="Intense Reference" w:uiPriority="32" w:qFormat="1"/><w:lsdException w:name="Book Title" w:uiPriority="33" w:qFormat="1"/><w:lsdException w:name="Bibliography" w:semiHidden="1" w:uiPriority="37" w:unhideWhenUsed="1"/><w:lsdException w:name="TOC Heading" w:semiHidden="1" w:uiPriority="39" w:unhideWhenUsed="1" w:qFormat="1"/><w:lsdException w:name="Plain Table 1" w:uiPriority="41"/><w:lsdException w:name="Plain Table 2" w:uiPriority="42"/><w:lsdException w:name="Plain Table 3" w:uiPriority="43"/><w:lsdException w:name="Plain Table 4" w:uiPriority="44"/><w:lsdException w:name="Plain Table 5" w:uiPriority="45"/><w:lsdException w:name="Grid Table Light" w:uiPriority="40"/><w:lsdException w:name="Grid Table 1 Light" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 1" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 1" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 1" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 1" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 1" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 1" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 1" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 2" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 2" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 2" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 2" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 2" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 2" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 2" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 3" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 3" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 3" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 3" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 3" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 3" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 3" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 4" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 4" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 4" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 4" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 4" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 4" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 4" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 5" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 5" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 5" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 5" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 5" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 5" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 5" w:uiPriority="52"/><w:lsdException w:name="Grid Table 1 Light Accent 6" w:uiPriority="46"/><w:lsdException w:name="Grid Table 2 Accent 6" w:uiPriority="47"/><w:lsdException w:name="Grid Table 3 Accent 6" w:uiPriority="48"/><w:lsdException w:name="Grid Table 4 Accent 6" w:uiPriority="49"/><w:lsdException w:name="Grid Table 5 Dark Accent 6" w:uiPriority="50"/><w:lsdException w:name="Grid Table 6 Colorful Accent 6" w:uiPriority="51"/><w:lsdException w:name="Grid Table 7 Colorful Accent 6" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light" w:uiPriority="46"/><w:lsdException w:name="List Table 2" w:uiPriority="47"/><w:lsdException w:name="List Table 3" w:uiPriority="48"/><w:lsdException w:name="List Table 4" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 1" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 1" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 1" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 1" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 1" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 1" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 1" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 2" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 2" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 2" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 2" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 2" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 2" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 2" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 3" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 3" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 3" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 3" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 3" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 3" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 3" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 4" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 4" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 4" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 4" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 4" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 4" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 4" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 5" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 5" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 5" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 5" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 5" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 5" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 5" w:uiPriority="52"/><w:lsdException w:name="List Table 1 Light Accent 6" w:uiPriority="46"/><w:lsdException w:name="List Table 2 Accent 6" w:uiPriority="47"/><w:lsdException w:name="List Table 3 Accent 6" w:uiPriority="48"/><w:lsdException w:name="List Table 4 Accent 6" w:uiPriority="49"/><w:lsdException w:name="List Table 5 Dark Accent 6" w:uiPriority="50"/><w:lsdException w:name="List Table 6 Colorful Accent 6" w:uiPriority="51"/><w:lsdException w:name="List Table 7 Colorful Accent 6" w:uiPriority="52"/><w:lsdException w:name="Mention" w:semiHidden="1" w:unhideWhenUsed="1"/><w:lsdException w:name="Smart Hyperlink" w:semiHidden="1" w:unhideWhenUsed="1"/></w:latentStyles><w:style w:type="paragraph" w:default="1" w:styleId="a"><w:name w:val="Normal"/><w:qFormat/><w:pPr><w:widowControl w:val="0"/><w:jc w:val="both"/></w:pPr></w:style><w:style w:type="character" w:default="1" w:styleId="a0"><w:name w:val="Default Paragraph Font"/><w:uiPriority w:val="1"/><w:semiHidden/><w:unhideWhenUsed/></w:style><w:style w:type="table" w:default="1" w:styleId="a1"><w:name w:val="Normal Table"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:tblPr><w:tblInd w:w="0" w:type="dxa"/><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style><w:style w:type="numbering" w:default="1" w:styleId="a2"><w:name w:val="No List"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/></w:style><w:style w:type="table" w:styleId="a3"><w:name w:val="Table Grid"/><w:basedOn w:val="a1"/><w:uiPriority w:val="39"/><w:rsid w:val="009026B1"/><w:tblPr><w:tblInd w:w="0" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideH w:val="single" w:sz="4" w:space="0" w:color="auto"/><w:insideV w:val="single" w:sz="4" w:space="0" w:color="auto"/></w:tblBorders><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style></w:styles></pkg:xmlData></pkg:part><pkg:part pkg:name="/docProps/app.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.extended-properties+xml" pkg:padding="256"><pkg:xmlData><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Template>Normal.dotm</Template><TotalTime>0</TotalTime><Pages>1</Pages><Words>20</Words><Characters>114</Characters><Application>Microsoft Macintosh Word</Application><DocSecurity>0</DocSecurity><Lines>1</Lines><Paragraphs>1</Paragraphs><ScaleCrop>false</ScaleCrop><HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>标题</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector size="1" baseType="lpstr"><vt:lpstr/></vt:vector></TitlesOfParts><LinksUpToDate>false</LinksUpToDate><CharactersWithSpaces>133</CharactersWithSpaces><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged><AppVersion>15.0000</AppVersion></Properties></pkg:xmlData></pkg:part></pkg:package>